// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CpuIntelMSR.proto
// Protobuf C++ Version: 6.33.1

#include "CpuIntelMSR.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace legion {
namespace messages {

inline constexpr CpuIntelMSR_VoltageSettings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        max_overvolt_{0u},
        max_undervolt_{0u},
        offset_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CpuIntelMSR_VoltageSettings::CpuIntelMSR_VoltageSettings(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CpuIntelMSR_VoltageSettings_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CpuIntelMSR_VoltageSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CpuIntelMSR_VoltageSettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuIntelMSR_VoltageSettingsDefaultTypeInternal() {}
  union {
    CpuIntelMSR_VoltageSettings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuIntelMSR_VoltageSettingsDefaultTypeInternal _CpuIntelMSR_VoltageSettings_default_instance_;

inline constexpr CpuIntelMSR::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        analogio_{nullptr},
        cache_{nullptr},
        cpu_{nullptr},
        gpu_{nullptr},
        uncore_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CpuIntelMSR::CpuIntelMSR(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CpuIntelMSR_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CpuIntelMSRDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CpuIntelMSRDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuIntelMSRDefaultTypeInternal() {}
  union {
    CpuIntelMSR _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuIntelMSRDefaultTypeInternal _CpuIntelMSR_default_instance_;
}  // namespace messages
}  // namespace legion
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_CpuIntelMSR_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_CpuIntelMSR_2eproto = nullptr;
const ::uint32_t
    TableStruct_CpuIntelMSR_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR_VoltageSettings, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR_VoltageSettings, _impl_.max_overvolt_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR_VoltageSettings, _impl_.max_undervolt_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR_VoltageSettings, _impl_.offset_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_.analogio_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_.cache_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_.cpu_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_.gpu_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CpuIntelMSR, _impl_.uncore_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::legion::messages::CpuIntelMSR_VoltageSettings)},
        {9, sizeof(::legion::messages::CpuIntelMSR)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::legion::messages::_CpuIntelMSR_VoltageSettings_default_instance_._instance,
    &::legion::messages::_CpuIntelMSR_default_instance_._instance,
};
const char descriptor_table_protodef_CpuIntelMSR_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021CpuIntelMSR.proto\022\017legion.messages\"\216\003\n"
    "\013CpuIntelMSR\022>\n\010analogio\030\001 \001(\0132,.legion."
    "messages.CpuIntelMSR.VoltageSettings\022;\n\005"
    "cache\030\002 \001(\0132,.legion.messages.CpuIntelMS"
    "R.VoltageSettings\0229\n\003cpu\030\003 \001(\0132,.legion."
    "messages.CpuIntelMSR.VoltageSettings\0229\n\003"
    "gpu\030\004 \001(\0132,.legion.messages.CpuIntelMSR."
    "VoltageSettings\022<\n\006uncore\030\005 \001(\0132,.legion"
    ".messages.CpuIntelMSR.VoltageSettings\032N\n"
    "\017VoltageSettings\022\024\n\014max_overvolt\030\001 \001(\r\022\025"
    "\n\rmax_undervolt\030\002 \001(\r\022\016\n\006offset\030\003 \001(\005b\010e"
    "ditionsp\351\007"
};
static ::absl::once_flag descriptor_table_CpuIntelMSR_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_CpuIntelMSR_2eproto = {
    false,
    false,
    450,
    descriptor_table_protodef_CpuIntelMSR_2eproto,
    "CpuIntelMSR.proto",
    &descriptor_table_CpuIntelMSR_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_CpuIntelMSR_2eproto::offsets,
    file_level_enum_descriptors_CpuIntelMSR_2eproto,
    file_level_service_descriptors_CpuIntelMSR_2eproto,
};
namespace legion {
namespace messages {
// ===================================================================

class CpuIntelMSR_VoltageSettings::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CpuIntelMSR_VoltageSettings>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_._has_bits_);
};

CpuIntelMSR_VoltageSettings::CpuIntelMSR_VoltageSettings(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuIntelMSR_VoltageSettings_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.CpuIntelMSR.VoltageSettings)
}
CpuIntelMSR_VoltageSettings::CpuIntelMSR_VoltageSettings(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CpuIntelMSR_VoltageSettings& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuIntelMSR_VoltageSettings_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CpuIntelMSR_VoltageSettings::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CpuIntelMSR_VoltageSettings::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, max_overvolt_),
           0,
           offsetof(Impl_, offset_) -
               offsetof(Impl_, max_overvolt_) +
               sizeof(Impl_::offset_));
}
CpuIntelMSR_VoltageSettings::~CpuIntelMSR_VoltageSettings() {
  // @@protoc_insertion_point(destructor:legion.messages.CpuIntelMSR.VoltageSettings)
  SharedDtor(*this);
}
inline void CpuIntelMSR_VoltageSettings::SharedDtor(MessageLite& self) {
  CpuIntelMSR_VoltageSettings& this_ = static_cast<CpuIntelMSR_VoltageSettings&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CpuIntelMSR_VoltageSettings::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CpuIntelMSR_VoltageSettings(arena);
}
constexpr auto CpuIntelMSR_VoltageSettings::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CpuIntelMSR_VoltageSettings),
                                            alignof(CpuIntelMSR_VoltageSettings));
}
constexpr auto CpuIntelMSR_VoltageSettings::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CpuIntelMSR_VoltageSettings_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CpuIntelMSR_VoltageSettings::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CpuIntelMSR_VoltageSettings>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CpuIntelMSR_VoltageSettings::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CpuIntelMSR_VoltageSettings>(), &CpuIntelMSR_VoltageSettings::ByteSizeLong,
              &CpuIntelMSR_VoltageSettings::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_._cached_size_),
          false,
      },
      &CpuIntelMSR_VoltageSettings::kDescriptorMethods,
      &descriptor_table_CpuIntelMSR_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CpuIntelMSR_VoltageSettings_class_data_ =
        CpuIntelMSR_VoltageSettings::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CpuIntelMSR_VoltageSettings::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CpuIntelMSR_VoltageSettings_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CpuIntelMSR_VoltageSettings_class_data_.tc_table);
  return CpuIntelMSR_VoltageSettings_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
CpuIntelMSR_VoltageSettings::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CpuIntelMSR_VoltageSettings_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 max_overvolt = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CpuIntelMSR_VoltageSettings, _impl_.max_overvolt_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.max_overvolt_)}},
    // uint32 max_undervolt = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CpuIntelMSR_VoltageSettings, _impl_.max_undervolt_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.max_undervolt_)}},
    // int32 offset = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CpuIntelMSR_VoltageSettings, _impl_.offset_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.offset_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 max_overvolt = 1;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.max_overvolt_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 max_undervolt = 2;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.max_undervolt_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // int32 offset = 3;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.offset_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CpuIntelMSR_VoltageSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.CpuIntelMSR.VoltageSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.max_overvolt_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.offset_) -
        reinterpret_cast<char*>(&_impl_.max_overvolt_)) + sizeof(_impl_.offset_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CpuIntelMSR_VoltageSettings::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CpuIntelMSR_VoltageSettings& this_ = static_cast<const CpuIntelMSR_VoltageSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CpuIntelMSR_VoltageSettings::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CpuIntelMSR_VoltageSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.CpuIntelMSR.VoltageSettings)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 max_overvolt = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_max_overvolt(), target);
  }

  // uint32 max_undervolt = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_max_undervolt(), target);
  }

  // int32 offset = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_offset(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.CpuIntelMSR.VoltageSettings)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CpuIntelMSR_VoltageSettings::ByteSizeLong(const MessageLite& base) {
  const CpuIntelMSR_VoltageSettings& this_ = static_cast<const CpuIntelMSR_VoltageSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CpuIntelMSR_VoltageSettings::ByteSizeLong() const {
  const CpuIntelMSR_VoltageSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.CpuIntelMSR.VoltageSettings)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // uint32 max_overvolt = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_max_overvolt());
    }
    // uint32 max_undervolt = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_max_undervolt());
    }
    // int32 offset = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_offset());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CpuIntelMSR_VoltageSettings::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CpuIntelMSR_VoltageSettings*>(&to_msg);
  auto& from = static_cast<const CpuIntelMSR_VoltageSettings&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.CpuIntelMSR.VoltageSettings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.max_overvolt_ = from._impl_.max_overvolt_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.max_undervolt_ = from._impl_.max_undervolt_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.offset_ = from._impl_.offset_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CpuIntelMSR_VoltageSettings::CopyFrom(const CpuIntelMSR_VoltageSettings& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.CpuIntelMSR.VoltageSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CpuIntelMSR_VoltageSettings::InternalSwap(CpuIntelMSR_VoltageSettings* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.offset_)
      + sizeof(CpuIntelMSR_VoltageSettings::_impl_.offset_)
      - PROTOBUF_FIELD_OFFSET(CpuIntelMSR_VoltageSettings, _impl_.max_overvolt_)>(
          reinterpret_cast<char*>(&_impl_.max_overvolt_),
          reinterpret_cast<char*>(&other->_impl_.max_overvolt_));
}

::google::protobuf::Metadata CpuIntelMSR_VoltageSettings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CpuIntelMSR::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CpuIntelMSR>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_._has_bits_);
};

CpuIntelMSR::CpuIntelMSR(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuIntelMSR_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.CpuIntelMSR)
}
PROTOBUF_NDEBUG_INLINE CpuIntelMSR::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::legion::messages::CpuIntelMSR& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CpuIntelMSR::CpuIntelMSR(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CpuIntelMSR& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuIntelMSR_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CpuIntelMSR* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.analogio_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.analogio_)
                : nullptr;
  _impl_.cache_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cache_)
                : nullptr;
  _impl_.cpu_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_)
                : nullptr;
  _impl_.gpu_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_)
                : nullptr;
  _impl_.uncore_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.uncore_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:legion.messages.CpuIntelMSR)
}
PROTOBUF_NDEBUG_INLINE CpuIntelMSR::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CpuIntelMSR::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, analogio_),
           0,
           offsetof(Impl_, uncore_) -
               offsetof(Impl_, analogio_) +
               sizeof(Impl_::uncore_));
}
CpuIntelMSR::~CpuIntelMSR() {
  // @@protoc_insertion_point(destructor:legion.messages.CpuIntelMSR)
  SharedDtor(*this);
}
inline void CpuIntelMSR::SharedDtor(MessageLite& self) {
  CpuIntelMSR& this_ = static_cast<CpuIntelMSR&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.analogio_;
  delete this_._impl_.cache_;
  delete this_._impl_.cpu_;
  delete this_._impl_.gpu_;
  delete this_._impl_.uncore_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CpuIntelMSR::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CpuIntelMSR(arena);
}
constexpr auto CpuIntelMSR::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CpuIntelMSR),
                                            alignof(CpuIntelMSR));
}
constexpr auto CpuIntelMSR::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CpuIntelMSR_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CpuIntelMSR::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CpuIntelMSR>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CpuIntelMSR::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CpuIntelMSR>(), &CpuIntelMSR::ByteSizeLong,
              &CpuIntelMSR::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_._cached_size_),
          false,
      },
      &CpuIntelMSR::kDescriptorMethods,
      &descriptor_table_CpuIntelMSR_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CpuIntelMSR_class_data_ =
        CpuIntelMSR::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CpuIntelMSR::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CpuIntelMSR_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CpuIntelMSR_class_data_.tc_table);
  return CpuIntelMSR_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 5, 0, 2>
CpuIntelMSR::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CpuIntelMSR_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .legion.messages.CpuIntelMSR.VoltageSettings analogio = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.analogio_)}},
    // .legion.messages.CpuIntelMSR.VoltageSettings cache = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.cache_)}},
    // .legion.messages.CpuIntelMSR.VoltageSettings cpu = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.cpu_)}},
    // .legion.messages.CpuIntelMSR.VoltageSettings gpu = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.gpu_)}},
    // .legion.messages.CpuIntelMSR.VoltageSettings uncore = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4,
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.uncore_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .legion.messages.CpuIntelMSR.VoltageSettings analogio = 1;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.analogio_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CpuIntelMSR.VoltageSettings cache = 2;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.cache_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CpuIntelMSR.VoltageSettings cpu = 3;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.cpu_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CpuIntelMSR.VoltageSettings gpu = 4;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.gpu_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CpuIntelMSR.VoltageSettings uncore = 5;
    {PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.uncore_), _Internal::kHasBitsOffset + 4, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CpuIntelMSR_VoltageSettings>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CpuIntelMSR::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.CpuIntelMSR)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.analogio_ != nullptr);
      _impl_.analogio_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.cache_ != nullptr);
      _impl_.cache_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.cpu_ != nullptr);
      _impl_.cpu_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.gpu_ != nullptr);
      _impl_.gpu_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.uncore_ != nullptr);
      _impl_.uncore_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CpuIntelMSR::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CpuIntelMSR& this_ = static_cast<const CpuIntelMSR&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CpuIntelMSR::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CpuIntelMSR& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.CpuIntelMSR)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .legion.messages.CpuIntelMSR.VoltageSettings analogio = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.analogio_, this_._impl_.analogio_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CpuIntelMSR.VoltageSettings cache = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.cache_, this_._impl_.cache_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CpuIntelMSR.VoltageSettings cpu = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.cpu_, this_._impl_.cpu_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CpuIntelMSR.VoltageSettings gpu = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.gpu_, this_._impl_.gpu_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CpuIntelMSR.VoltageSettings uncore = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.uncore_, this_._impl_.uncore_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.CpuIntelMSR)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CpuIntelMSR::ByteSizeLong(const MessageLite& base) {
  const CpuIntelMSR& this_ = static_cast<const CpuIntelMSR&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CpuIntelMSR::ByteSizeLong() const {
  const CpuIntelMSR& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.CpuIntelMSR)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // .legion.messages.CpuIntelMSR.VoltageSettings analogio = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.analogio_);
    }
    // .legion.messages.CpuIntelMSR.VoltageSettings cache = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cache_);
    }
    // .legion.messages.CpuIntelMSR.VoltageSettings cpu = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_);
    }
    // .legion.messages.CpuIntelMSR.VoltageSettings gpu = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.gpu_);
    }
    // .legion.messages.CpuIntelMSR.VoltageSettings uncore = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.uncore_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CpuIntelMSR::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CpuIntelMSR*>(&to_msg);
  auto& from = static_cast<const CpuIntelMSR&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.CpuIntelMSR)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.analogio_ != nullptr);
      if (_this->_impl_.analogio_ == nullptr) {
        _this->_impl_.analogio_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.analogio_);
      } else {
        _this->_impl_.analogio_->MergeFrom(*from._impl_.analogio_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.cache_ != nullptr);
      if (_this->_impl_.cache_ == nullptr) {
        _this->_impl_.cache_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cache_);
      } else {
        _this->_impl_.cache_->MergeFrom(*from._impl_.cache_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.cpu_ != nullptr);
      if (_this->_impl_.cpu_ == nullptr) {
        _this->_impl_.cpu_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_);
      } else {
        _this->_impl_.cpu_->MergeFrom(*from._impl_.cpu_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.gpu_ != nullptr);
      if (_this->_impl_.gpu_ == nullptr) {
        _this->_impl_.gpu_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_);
      } else {
        _this->_impl_.gpu_->MergeFrom(*from._impl_.gpu_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.uncore_ != nullptr);
      if (_this->_impl_.uncore_ == nullptr) {
        _this->_impl_.uncore_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.uncore_);
      } else {
        _this->_impl_.uncore_->MergeFrom(*from._impl_.uncore_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CpuIntelMSR::CopyFrom(const CpuIntelMSR& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.CpuIntelMSR)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CpuIntelMSR::InternalSwap(CpuIntelMSR* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.uncore_)
      + sizeof(CpuIntelMSR::_impl_.uncore_)
      - PROTOBUF_FIELD_OFFSET(CpuIntelMSR, _impl_.analogio_)>(
          reinterpret_cast<char*>(&_impl_.analogio_),
          reinterpret_cast<char*>(&other->_impl_.analogio_));
}

::google::protobuf::Metadata CpuIntelMSR::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_CpuIntelMSR_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
