// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CpuPower.proto
// Protobuf C++ Version: 6.33.1

#include "CpuPower.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace legion {
namespace messages {

inline constexpr CPUPower_Limit_Descriptor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        steps_{},
        _steps_cached_byte_size_{0},
        default_value_{0u},
        display_name_{0u},
        min_value_{0u},
        max_value_{0u},
        scalar_increment_{0u},
        type_{0u},
        supported_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CPUPower_Limit_Descriptor::CPUPower_Limit_Descriptor(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CPUPower_Limit_Descriptor_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CPUPower_Limit_DescriptorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPUPower_Limit_DescriptorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPUPower_Limit_DescriptorDefaultTypeInternal() {}
  union {
    CPUPower_Limit_Descriptor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPUPower_Limit_DescriptorDefaultTypeInternal _CPUPower_Limit_Descriptor_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::MapEntry(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal _CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_default_instance_;

inline constexpr CPUPower_Limit::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        current_value_{0u},
        mode_descriptor_map_{} {}

template <typename>
PROTOBUF_CONSTEXPR CPUPower_Limit::CPUPower_Limit(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CPUPower_Limit_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CPUPower_LimitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPUPower_LimitDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPUPower_LimitDefaultTypeInternal() {}
  union {
    CPUPower_Limit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPUPower_LimitDefaultTypeInternal _CPUPower_Limit_default_instance_;

inline constexpr CPUPower::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        apus_pptp_limit_{nullptr},
        cpu_clp_limit_{nullptr},
        cpu_ltp_limit_{nullptr},
        cpu_pl1_tau_{nullptr},
        cpu_pp_limit_{nullptr},
        cpu_stp_limit_{nullptr},
        cpu_tmp_limit_{nullptr},
        gpu_to_cpu_dynamic_boost_{nullptr},
        gpu_total_onac_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CPUPower::CPUPower(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CPUPower_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CPUPowerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPUPowerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPUPowerDefaultTypeInternal() {}
  union {
    CPUPower _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPUPowerDefaultTypeInternal _CPUPower_default_instance_;
}  // namespace messages
}  // namespace legion
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_CpuPower_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_CpuPower_2eproto = nullptr;
const ::uint32_t
    TableStruct_CpuPower_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.default_value_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.display_name_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.min_value_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.max_value_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.scalar_increment_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.steps_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_Descriptor, _impl_.supported_),
        1,
        2,
        3,
        4,
        5,
        0,
        6,
        7,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit, _impl_.current_value_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower_Limit, _impl_.mode_descriptor_map_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.apus_pptp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_clp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_ltp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_pl1_tau_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_pp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_stp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.cpu_tmp_limit_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.gpu_to_cpu_dynamic_boost_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::CPUPower, _impl_.gpu_total_onac_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::legion::messages::CPUPower_Limit_Descriptor)},
        {19, sizeof(::legion::messages::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse)},
        {26, sizeof(::legion::messages::CPUPower_Limit)},
        {33, sizeof(::legion::messages::CPUPower)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::legion::messages::_CPUPower_Limit_Descriptor_default_instance_._instance,
    &::legion::messages::_CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_default_instance_._instance,
    &::legion::messages::_CPUPower_Limit_default_instance_._instance,
    &::legion::messages::_CPUPower_default_instance_._instance,
};
const char descriptor_table_protodef_CpuPower_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016CpuPower.proto\022\017legion.messages\"\225\007\n\010CP"
    "UPower\0228\n\017apus_pptp_limit\030\001 \001(\0132\037.legion"
    ".messages.CPUPower.Limit\0226\n\rcpu_clp_limi"
    "t\030\002 \001(\0132\037.legion.messages.CPUPower.Limit"
    "\0226\n\rcpu_ltp_limit\030\003 \001(\0132\037.legion.message"
    "s.CPUPower.Limit\0224\n\013cpu_pl1_tau\030\004 \001(\0132\037."
    "legion.messages.CPUPower.Limit\0225\n\014cpu_pp"
    "_limit\030\005 \001(\0132\037.legion.messages.CPUPower."
    "Limit\0226\n\rcpu_stp_limit\030\006 \001(\0132\037.legion.me"
    "ssages.CPUPower.Limit\0226\n\rcpu_tmp_limit\030\007"
    " \001(\0132\037.legion.messages.CPUPower.Limit\022A\n"
    "\030gpu_to_cpu_dynamic_boost\030\010 \001(\0132\037.legion"
    ".messages.CPUPower.Limit\0227\n\016gpu_total_on"
    "ac\030\t \001(\0132\037.legion.messages.CPUPower.Limi"
    "t\032\205\003\n\005Limit\022\025\n\rcurrent_value\030\001 \001(\r\022S\n\023mo"
    "de_descriptor_map\030\002 \003(\01326.legion.message"
    "s.CPUPower.Limit.ModeDescriptorMapEntry\032"
    "\251\001\n\nDescriptor\022\025\n\rdefault_value\030\001 \001(\r\022\024\n"
    "\014display_name\030\002 \001(\r\022\021\n\tmin_value\030\003 \001(\r\022\021"
    "\n\tmax_value\030\004 \001(\r\022\030\n\020scalar_increment\030\005 "
    "\001(\r\022\r\n\005steps\030\006 \003(\r\022\014\n\004type\030\007 \001(\r\022\021\n\tsupp"
    "orted\030\010 \001(\r\032d\n\026ModeDescriptorMapEntry\022\013\n"
    "\003key\030\001 \001(\005\0229\n\005value\030\002 \001(\0132*.legion.messa"
    "ges.CPUPower.Limit.Descriptor:\0028\001b\010editi"
    "onsp\351\007"
};
static ::absl::once_flag descriptor_table_CpuPower_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_CpuPower_2eproto = {
    false,
    false,
    966,
    descriptor_table_protodef_CpuPower_2eproto,
    "CpuPower.proto",
    &descriptor_table_CpuPower_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_CpuPower_2eproto::offsets,
    file_level_enum_descriptors_CpuPower_2eproto,
    file_level_service_descriptors_CpuPower_2eproto,
};
namespace legion {
namespace messages {
// ===================================================================

class CPUPower_Limit_Descriptor::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CPUPower_Limit_Descriptor>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_._has_bits_);
};

CPUPower_Limit_Descriptor::CPUPower_Limit_Descriptor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_Limit_Descriptor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.CPUPower.Limit.Descriptor)
}
PROTOBUF_NDEBUG_INLINE CPUPower_Limit_Descriptor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::legion::messages::CPUPower_Limit_Descriptor& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        steps_{visibility, arena, from.steps_},
        _steps_cached_byte_size_{0} {}

CPUPower_Limit_Descriptor::CPUPower_Limit_Descriptor(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CPUPower_Limit_Descriptor& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_Limit_Descriptor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CPUPower_Limit_Descriptor* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, default_value_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, default_value_),
           offsetof(Impl_, supported_) -
               offsetof(Impl_, default_value_) +
               sizeof(Impl_::supported_));

  // @@protoc_insertion_point(copy_constructor:legion.messages.CPUPower.Limit.Descriptor)
}
PROTOBUF_NDEBUG_INLINE CPUPower_Limit_Descriptor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        steps_{visibility, arena},
        _steps_cached_byte_size_{0} {}

inline void CPUPower_Limit_Descriptor::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, default_value_),
           0,
           offsetof(Impl_, supported_) -
               offsetof(Impl_, default_value_) +
               sizeof(Impl_::supported_));
}
CPUPower_Limit_Descriptor::~CPUPower_Limit_Descriptor() {
  // @@protoc_insertion_point(destructor:legion.messages.CPUPower.Limit.Descriptor)
  SharedDtor(*this);
}
inline void CPUPower_Limit_Descriptor::SharedDtor(MessageLite& self) {
  CPUPower_Limit_Descriptor& this_ = static_cast<CPUPower_Limit_Descriptor&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CPUPower_Limit_Descriptor::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CPUPower_Limit_Descriptor(arena);
}
constexpr auto CPUPower_Limit_Descriptor::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.steps_) +
          decltype(CPUPower_Limit_Descriptor::_impl_.steps_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CPUPower_Limit_Descriptor), alignof(CPUPower_Limit_Descriptor), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CPUPower_Limit_Descriptor::PlacementNew_,
                                 sizeof(CPUPower_Limit_Descriptor),
                                 alignof(CPUPower_Limit_Descriptor));
  }
}
constexpr auto CPUPower_Limit_Descriptor::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CPUPower_Limit_Descriptor_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CPUPower_Limit_Descriptor::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CPUPower_Limit_Descriptor>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CPUPower_Limit_Descriptor::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CPUPower_Limit_Descriptor>(), &CPUPower_Limit_Descriptor::ByteSizeLong,
              &CPUPower_Limit_Descriptor::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_._cached_size_),
          false,
      },
      &CPUPower_Limit_Descriptor::kDescriptorMethods,
      &descriptor_table_CpuPower_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CPUPower_Limit_Descriptor_class_data_ =
        CPUPower_Limit_Descriptor::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CPUPower_Limit_Descriptor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CPUPower_Limit_Descriptor_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CPUPower_Limit_Descriptor_class_data_.tc_table);
  return CPUPower_Limit_Descriptor_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 0, 2>
CPUPower_Limit_Descriptor::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CPUPower_Limit_Descriptor_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit_Descriptor>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 supported = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.supported_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.supported_)}},
    // uint32 default_value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.default_value_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.default_value_)}},
    // uint32 display_name = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.display_name_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.display_name_)}},
    // uint32 min_value = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.min_value_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.min_value_)}},
    // uint32 max_value = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.max_value_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.max_value_)}},
    // uint32 scalar_increment = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.scalar_increment_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.scalar_increment_)}},
    // repeated uint32 steps = 6;
    {::_pbi::TcParser::FastV32P1,
     {50, 0, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.steps_)}},
    // uint32 type = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_Descriptor, _impl_.type_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 default_value = 1;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.default_value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 display_name = 2;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.display_name_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 min_value = 3;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.min_value_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 max_value = 4;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.max_value_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 scalar_increment = 5;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.scalar_increment_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint32 steps = 6;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.steps_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // uint32 type = 7;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.type_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 supported = 8;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.supported_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CPUPower_Limit_Descriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.CPUPower.Limit.Descriptor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.steps_.Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000feU)) {
    ::memset(&_impl_.default_value_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.supported_) -
        reinterpret_cast<char*>(&_impl_.default_value_)) + sizeof(_impl_.supported_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CPUPower_Limit_Descriptor::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CPUPower_Limit_Descriptor& this_ = static_cast<const CPUPower_Limit_Descriptor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CPUPower_Limit_Descriptor::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CPUPower_Limit_Descriptor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.CPUPower.Limit.Descriptor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 default_value = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_default_value(), target);
  }

  // uint32 display_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_display_name(), target);
  }

  // uint32 min_value = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_min_value(), target);
  }

  // uint32 max_value = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_max_value(), target);
  }

  // uint32 scalar_increment = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_scalar_increment(), target);
  }

  // repeated uint32 steps = 6;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._steps_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            6, this_._internal_steps(), byte_size, target);
      }
    }
  }

  // uint32 type = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this_._internal_type(), target);
  }

  // uint32 supported = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        8, this_._internal_supported(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.CPUPower.Limit.Descriptor)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CPUPower_Limit_Descriptor::ByteSizeLong(const MessageLite& base) {
  const CPUPower_Limit_Descriptor& this_ = static_cast<const CPUPower_Limit_Descriptor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CPUPower_Limit_Descriptor::ByteSizeLong() const {
  const CPUPower_Limit_Descriptor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.CPUPower.Limit.Descriptor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated uint32 steps = 6;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_steps(), 1,
              this_._impl_._steps_cached_byte_size_);
    }
    // uint32 default_value = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_default_value());
    }
    // uint32 display_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_display_name());
    }
    // uint32 min_value = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_min_value());
    }
    // uint32 max_value = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_max_value());
    }
    // uint32 scalar_increment = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_scalar_increment());
    }
    // uint32 type = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_type());
    }
    // uint32 supported = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_supported());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CPUPower_Limit_Descriptor::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CPUPower_Limit_Descriptor*>(&to_msg);
  auto& from = static_cast<const CPUPower_Limit_Descriptor&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.CPUPower.Limit.Descriptor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_steps()->MergeFrom(from._internal_steps());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.default_value_ = from._impl_.default_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.display_name_ = from._impl_.display_name_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.min_value_ = from._impl_.min_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.max_value_ = from._impl_.max_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.scalar_increment_ = from._impl_.scalar_increment_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.supported_ = from._impl_.supported_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CPUPower_Limit_Descriptor::CopyFrom(const CPUPower_Limit_Descriptor& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.CPUPower.Limit.Descriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CPUPower_Limit_Descriptor::InternalSwap(CPUPower_Limit_Descriptor* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.steps_.InternalSwap(&other->_impl_.steps_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.supported_)
      + sizeof(CPUPower_Limit_Descriptor::_impl_.supported_)
      - PROTOBUF_FIELD_OFFSET(CPUPower_Limit_Descriptor, _impl_.default_value_)>(
          reinterpret_cast<char*>(&_impl_.default_value_),
          reinterpret_cast<char*>(&other->_impl_.default_value_));
}

::google::protobuf::Metadata CPUPower_Limit_Descriptor::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse()
    : SuperType(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.base()) {}
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse() : SuperType() {}
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(arena);
}
constexpr auto CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse),
                                            alignof(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse));
}
constexpr auto CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_CpuPower_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_ =
        CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.tc_table);
  return CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .legion.messages.CPUPower.Limit.Descriptor value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.key_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .legion.messages.CPUPower.Limit.Descriptor value = 2;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit_Descriptor>()},
  }},
  {{
  }},
};
// ===================================================================

class CPUPower_Limit::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CPUPower_Limit>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_._has_bits_);
};

CPUPower_Limit::CPUPower_Limit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_Limit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.CPUPower.Limit)
}
PROTOBUF_NDEBUG_INLINE CPUPower_Limit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::legion::messages::CPUPower_Limit& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        mode_descriptor_map_{visibility, arena, from.mode_descriptor_map_} {}

CPUPower_Limit::CPUPower_Limit(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CPUPower_Limit& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_Limit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CPUPower_Limit* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.current_value_ = from._impl_.current_value_;

  // @@protoc_insertion_point(copy_constructor:legion.messages.CPUPower.Limit)
}
PROTOBUF_NDEBUG_INLINE CPUPower_Limit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        mode_descriptor_map_{visibility, arena} {}

inline void CPUPower_Limit::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.current_value_ = {};
}
CPUPower_Limit::~CPUPower_Limit() {
  // @@protoc_insertion_point(destructor:legion.messages.CPUPower.Limit)
  SharedDtor(*this);
}
inline void CPUPower_Limit::SharedDtor(MessageLite& self) {
  CPUPower_Limit& this_ = static_cast<CPUPower_Limit&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CPUPower_Limit::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CPUPower_Limit(arena);
}
constexpr auto CPUPower_Limit::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_.mode_descriptor_map_) +
          decltype(CPUPower_Limit::_impl_.mode_descriptor_map_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CPUPower_Limit), alignof(CPUPower_Limit), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CPUPower_Limit::PlacementNew_,
                                 sizeof(CPUPower_Limit),
                                 alignof(CPUPower_Limit));
  }
}
constexpr auto CPUPower_Limit::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CPUPower_Limit_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CPUPower_Limit::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CPUPower_Limit>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CPUPower_Limit::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CPUPower_Limit>(), &CPUPower_Limit::ByteSizeLong,
              &CPUPower_Limit::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_._cached_size_),
          false,
      },
      &CPUPower_Limit::kDescriptorMethods,
      &descriptor_table_CpuPower_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CPUPower_Limit_class_data_ =
        CPUPower_Limit::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CPUPower_Limit::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CPUPower_Limit_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CPUPower_Limit_class_data_.tc_table);
  return CPUPower_Limit_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2>
CPUPower_Limit::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CPUPower_Limit_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 current_value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CPUPower_Limit, _impl_.current_value_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_.current_value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 current_value = 1;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_.current_value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // map<int32, .legion.messages.CPUPower.Limit.Descriptor> mode_descriptor_map = 2;
    {PROTOBUF_FIELD_OFFSET(CPUPower_Limit, _impl_.mode_descriptor_map_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(
          0, 0, 5, 11, 0)},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit_Descriptor>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CPUPower_Limit::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.CPUPower.Limit)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    _impl_.current_value_ = 0u;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.mode_descriptor_map_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CPUPower_Limit::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CPUPower_Limit& this_ = static_cast<const CPUPower_Limit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CPUPower_Limit::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CPUPower_Limit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.CPUPower.Limit)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 current_value = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_current_value(), target);
  }

  // map<int32, .legion.messages.CPUPower.Limit.Descriptor> mode_descriptor_map = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_mode_descriptor_map().empty()) {
      using MapType = ::google::protobuf::Map<::int32_t, ::legion::messages::CPUPower_Limit_Descriptor>;
      using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::legion::messages::CPUPower_Limit_Descriptor,
                                     _pbi::WireFormatLite::TYPE_INT32,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_mode_descriptor_map();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.CPUPower.Limit)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CPUPower_Limit::ByteSizeLong(const MessageLite& base) {
  const CPUPower_Limit& this_ = static_cast<const CPUPower_Limit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CPUPower_Limit::ByteSizeLong() const {
  const CPUPower_Limit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.CPUPower.Limit)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // uint32 current_value = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_current_value());
    }
    // map<int32, .legion.messages.CPUPower.Limit.Descriptor> mode_descriptor_map = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_mode_descriptor_map_size());
      for (const auto& entry : this_._internal_mode_descriptor_map()) {
        total_size += _pbi::MapEntryFuncs<::int32_t, ::legion::messages::CPUPower_Limit_Descriptor,
                                       _pbi::WireFormatLite::TYPE_INT32,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CPUPower_Limit::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CPUPower_Limit*>(&to_msg);
  auto& from = static_cast<const CPUPower_Limit&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.CPUPower.Limit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.current_value_ = from._impl_.current_value_;
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_impl_.mode_descriptor_map_.MergeFrom(from._impl_.mode_descriptor_map_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CPUPower_Limit::CopyFrom(const CPUPower_Limit& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.CPUPower.Limit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CPUPower_Limit::InternalSwap(CPUPower_Limit* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.current_value_, other->_impl_.current_value_);
  _impl_.mode_descriptor_map_.InternalSwap(&other->_impl_.mode_descriptor_map_);
}

::google::protobuf::Metadata CPUPower_Limit::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CPUPower::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CPUPower>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CPUPower, _impl_._has_bits_);
};

CPUPower::CPUPower(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.CPUPower)
}
PROTOBUF_NDEBUG_INLINE CPUPower::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::legion::messages::CPUPower& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CPUPower::CPUPower(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CPUPower& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CPUPower_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CPUPower* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.apus_pptp_limit_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.apus_pptp_limit_)
                : nullptr;
  _impl_.cpu_clp_limit_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_clp_limit_)
                : nullptr;
  _impl_.cpu_ltp_limit_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_ltp_limit_)
                : nullptr;
  _impl_.cpu_pl1_tau_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_pl1_tau_)
                : nullptr;
  _impl_.cpu_pp_limit_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_pp_limit_)
                : nullptr;
  _impl_.cpu_stp_limit_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_stp_limit_)
                : nullptr;
  _impl_.cpu_tmp_limit_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_tmp_limit_)
                : nullptr;
  _impl_.gpu_to_cpu_dynamic_boost_ = (CheckHasBit(cached_has_bits, 0x00000080U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_to_cpu_dynamic_boost_)
                : nullptr;
  _impl_.gpu_total_onac_ = (CheckHasBit(cached_has_bits, 0x00000100U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_total_onac_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:legion.messages.CPUPower)
}
PROTOBUF_NDEBUG_INLINE CPUPower::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CPUPower::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, apus_pptp_limit_),
           0,
           offsetof(Impl_, gpu_total_onac_) -
               offsetof(Impl_, apus_pptp_limit_) +
               sizeof(Impl_::gpu_total_onac_));
}
CPUPower::~CPUPower() {
  // @@protoc_insertion_point(destructor:legion.messages.CPUPower)
  SharedDtor(*this);
}
inline void CPUPower::SharedDtor(MessageLite& self) {
  CPUPower& this_ = static_cast<CPUPower&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.apus_pptp_limit_;
  delete this_._impl_.cpu_clp_limit_;
  delete this_._impl_.cpu_ltp_limit_;
  delete this_._impl_.cpu_pl1_tau_;
  delete this_._impl_.cpu_pp_limit_;
  delete this_._impl_.cpu_stp_limit_;
  delete this_._impl_.cpu_tmp_limit_;
  delete this_._impl_.gpu_to_cpu_dynamic_boost_;
  delete this_._impl_.gpu_total_onac_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CPUPower::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CPUPower(arena);
}
constexpr auto CPUPower::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CPUPower),
                                            alignof(CPUPower));
}
constexpr auto CPUPower::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CPUPower_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CPUPower::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CPUPower>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CPUPower::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CPUPower>(), &CPUPower::ByteSizeLong,
              &CPUPower::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CPUPower, _impl_._cached_size_),
          false,
      },
      &CPUPower::kDescriptorMethods,
      &descriptor_table_CpuPower_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CPUPower_class_data_ =
        CPUPower::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CPUPower::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CPUPower_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CPUPower_class_data_.tc_table);
  return CPUPower_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 9, 0, 2>
CPUPower::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CPUPower, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    9,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CPUPower_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::CPUPower>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .legion.messages.CPUPower.Limit apus_pptp_limit = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.apus_pptp_limit_)}},
    // .legion.messages.CPUPower.Limit cpu_clp_limit = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_clp_limit_)}},
    // .legion.messages.CPUPower.Limit cpu_ltp_limit = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_ltp_limit_)}},
    // .legion.messages.CPUPower.Limit cpu_pl1_tau = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_pl1_tau_)}},
    // .legion.messages.CPUPower.Limit cpu_pp_limit = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_pp_limit_)}},
    // .legion.messages.CPUPower.Limit cpu_stp_limit = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 5, 5,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_stp_limit_)}},
    // .legion.messages.CPUPower.Limit cpu_tmp_limit = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 6, 6,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_tmp_limit_)}},
    // .legion.messages.CPUPower.Limit gpu_to_cpu_dynamic_boost = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 7, 7,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.gpu_to_cpu_dynamic_boost_)}},
    // .legion.messages.CPUPower.Limit gpu_total_onac = 9;
    {::_pbi::TcParser::FastMtS1,
     {74, 8, 8,
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.gpu_total_onac_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .legion.messages.CPUPower.Limit apus_pptp_limit = 1;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.apus_pptp_limit_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_clp_limit = 2;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_clp_limit_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_ltp_limit = 3;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_ltp_limit_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_pl1_tau = 4;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_pl1_tau_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_pp_limit = 5;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_pp_limit_), _Internal::kHasBitsOffset + 4, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_stp_limit = 6;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_stp_limit_), _Internal::kHasBitsOffset + 5, 5, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit cpu_tmp_limit = 7;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.cpu_tmp_limit_), _Internal::kHasBitsOffset + 6, 6, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit gpu_to_cpu_dynamic_boost = 8;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.gpu_to_cpu_dynamic_boost_), _Internal::kHasBitsOffset + 7, 7, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.CPUPower.Limit gpu_total_onac = 9;
    {PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.gpu_total_onac_), _Internal::kHasBitsOffset + 8, 8, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
      {::_pbi::TcParser::GetTable<::legion::messages::CPUPower_Limit>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CPUPower::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.CPUPower)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.apus_pptp_limit_ != nullptr);
      _impl_.apus_pptp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.cpu_clp_limit_ != nullptr);
      _impl_.cpu_clp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.cpu_ltp_limit_ != nullptr);
      _impl_.cpu_ltp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.cpu_pl1_tau_ != nullptr);
      _impl_.cpu_pl1_tau_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.cpu_pp_limit_ != nullptr);
      _impl_.cpu_pp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.cpu_stp_limit_ != nullptr);
      _impl_.cpu_stp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.cpu_tmp_limit_ != nullptr);
      _impl_.cpu_tmp_limit_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(_impl_.gpu_to_cpu_dynamic_boost_ != nullptr);
      _impl_.gpu_to_cpu_dynamic_boost_->Clear();
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    ABSL_DCHECK(_impl_.gpu_total_onac_ != nullptr);
    _impl_.gpu_total_onac_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CPUPower::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CPUPower& this_ = static_cast<const CPUPower&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CPUPower::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CPUPower& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.CPUPower)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .legion.messages.CPUPower.Limit apus_pptp_limit = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.apus_pptp_limit_, this_._impl_.apus_pptp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_clp_limit = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.cpu_clp_limit_, this_._impl_.cpu_clp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_ltp_limit = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.cpu_ltp_limit_, this_._impl_.cpu_ltp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_pl1_tau = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.cpu_pl1_tau_, this_._impl_.cpu_pl1_tau_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_pp_limit = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.cpu_pp_limit_, this_._impl_.cpu_pp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_stp_limit = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.cpu_stp_limit_, this_._impl_.cpu_stp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit cpu_tmp_limit = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.cpu_tmp_limit_, this_._impl_.cpu_tmp_limit_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit gpu_to_cpu_dynamic_boost = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.gpu_to_cpu_dynamic_boost_, this_._impl_.gpu_to_cpu_dynamic_boost_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.CPUPower.Limit gpu_total_onac = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *this_._impl_.gpu_total_onac_, this_._impl_.gpu_total_onac_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.CPUPower)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CPUPower::ByteSizeLong(const MessageLite& base) {
  const CPUPower& this_ = static_cast<const CPUPower&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CPUPower::ByteSizeLong() const {
  const CPUPower& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.CPUPower)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // .legion.messages.CPUPower.Limit apus_pptp_limit = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.apus_pptp_limit_);
    }
    // .legion.messages.CPUPower.Limit cpu_clp_limit = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_clp_limit_);
    }
    // .legion.messages.CPUPower.Limit cpu_ltp_limit = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_ltp_limit_);
    }
    // .legion.messages.CPUPower.Limit cpu_pl1_tau = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_pl1_tau_);
    }
    // .legion.messages.CPUPower.Limit cpu_pp_limit = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_pp_limit_);
    }
    // .legion.messages.CPUPower.Limit cpu_stp_limit = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_stp_limit_);
    }
    // .legion.messages.CPUPower.Limit cpu_tmp_limit = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cpu_tmp_limit_);
    }
    // .legion.messages.CPUPower.Limit gpu_to_cpu_dynamic_boost = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.gpu_to_cpu_dynamic_boost_);
    }
  }
   {
    // .legion.messages.CPUPower.Limit gpu_total_onac = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.gpu_total_onac_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CPUPower::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CPUPower*>(&to_msg);
  auto& from = static_cast<const CPUPower&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.CPUPower)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.apus_pptp_limit_ != nullptr);
      if (_this->_impl_.apus_pptp_limit_ == nullptr) {
        _this->_impl_.apus_pptp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.apus_pptp_limit_);
      } else {
        _this->_impl_.apus_pptp_limit_->MergeFrom(*from._impl_.apus_pptp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.cpu_clp_limit_ != nullptr);
      if (_this->_impl_.cpu_clp_limit_ == nullptr) {
        _this->_impl_.cpu_clp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_clp_limit_);
      } else {
        _this->_impl_.cpu_clp_limit_->MergeFrom(*from._impl_.cpu_clp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.cpu_ltp_limit_ != nullptr);
      if (_this->_impl_.cpu_ltp_limit_ == nullptr) {
        _this->_impl_.cpu_ltp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_ltp_limit_);
      } else {
        _this->_impl_.cpu_ltp_limit_->MergeFrom(*from._impl_.cpu_ltp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.cpu_pl1_tau_ != nullptr);
      if (_this->_impl_.cpu_pl1_tau_ == nullptr) {
        _this->_impl_.cpu_pl1_tau_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_pl1_tau_);
      } else {
        _this->_impl_.cpu_pl1_tau_->MergeFrom(*from._impl_.cpu_pl1_tau_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.cpu_pp_limit_ != nullptr);
      if (_this->_impl_.cpu_pp_limit_ == nullptr) {
        _this->_impl_.cpu_pp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_pp_limit_);
      } else {
        _this->_impl_.cpu_pp_limit_->MergeFrom(*from._impl_.cpu_pp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.cpu_stp_limit_ != nullptr);
      if (_this->_impl_.cpu_stp_limit_ == nullptr) {
        _this->_impl_.cpu_stp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_stp_limit_);
      } else {
        _this->_impl_.cpu_stp_limit_->MergeFrom(*from._impl_.cpu_stp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.cpu_tmp_limit_ != nullptr);
      if (_this->_impl_.cpu_tmp_limit_ == nullptr) {
        _this->_impl_.cpu_tmp_limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cpu_tmp_limit_);
      } else {
        _this->_impl_.cpu_tmp_limit_->MergeFrom(*from._impl_.cpu_tmp_limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(from._impl_.gpu_to_cpu_dynamic_boost_ != nullptr);
      if (_this->_impl_.gpu_to_cpu_dynamic_boost_ == nullptr) {
        _this->_impl_.gpu_to_cpu_dynamic_boost_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_to_cpu_dynamic_boost_);
      } else {
        _this->_impl_.gpu_to_cpu_dynamic_boost_->MergeFrom(*from._impl_.gpu_to_cpu_dynamic_boost_);
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    ABSL_DCHECK(from._impl_.gpu_total_onac_ != nullptr);
    if (_this->_impl_.gpu_total_onac_ == nullptr) {
      _this->_impl_.gpu_total_onac_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gpu_total_onac_);
    } else {
      _this->_impl_.gpu_total_onac_->MergeFrom(*from._impl_.gpu_total_onac_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CPUPower::CopyFrom(const CPUPower& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.CPUPower)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CPUPower::InternalSwap(CPUPower* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.gpu_total_onac_)
      + sizeof(CPUPower::_impl_.gpu_total_onac_)
      - PROTOBUF_FIELD_OFFSET(CPUPower, _impl_.apus_pptp_limit_)>(
          reinterpret_cast<char*>(&_impl_.apus_pptp_limit_),
          reinterpret_cast<char*>(&other->_impl_.apus_pptp_limit_));
}

::google::protobuf::Metadata CPUPower::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_CpuPower_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
