// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CpuPowerRapl.proto
// Protobuf C++ Version: 6.33.1

#ifndef CpuPowerRapl_2eproto_2epb_2eh
#define CpuPowerRapl_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_CpuPowerRapl_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_CpuPowerRapl_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_CpuPowerRapl_2eproto;
}  // extern "C"
namespace legion {
namespace messages {
class CPUPowerRapl;
struct CPUPowerRaplDefaultTypeInternal;
extern CPUPowerRaplDefaultTypeInternal _CPUPowerRapl_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CPUPowerRapl_class_data_;
class CPUPowerRapl_Limit;
struct CPUPowerRapl_LimitDefaultTypeInternal;
extern CPUPowerRapl_LimitDefaultTypeInternal _CPUPowerRapl_Limit_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CPUPowerRapl_Limit_class_data_;
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace legion {
namespace messages {

// ===================================================================


// -------------------------------------------------------------------

class CPUPowerRapl_Limit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.CPUPowerRapl.Limit) */ {
 public:
  inline CPUPowerRapl_Limit() : CPUPowerRapl_Limit(nullptr) {}
  ~CPUPowerRapl_Limit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CPUPowerRapl_Limit* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CPUPowerRapl_Limit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CPUPowerRapl_Limit(::google::protobuf::internal::ConstantInitialized);

  inline CPUPowerRapl_Limit(const CPUPowerRapl_Limit& from) : CPUPowerRapl_Limit(nullptr, from) {}
  inline CPUPowerRapl_Limit(CPUPowerRapl_Limit&& from) noexcept
      : CPUPowerRapl_Limit(nullptr, ::std::move(from)) {}
  inline CPUPowerRapl_Limit& operator=(const CPUPowerRapl_Limit& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPUPowerRapl_Limit& operator=(CPUPowerRapl_Limit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CPUPowerRapl_Limit& default_instance() {
    return *reinterpret_cast<const CPUPowerRapl_Limit*>(
        &_CPUPowerRapl_Limit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CPUPowerRapl_Limit& a, CPUPowerRapl_Limit& b) { a.Swap(&b); }
  inline void Swap(CPUPowerRapl_Limit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPUPowerRapl_Limit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CPUPowerRapl_Limit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CPUPowerRapl_Limit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CPUPowerRapl_Limit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CPUPowerRapl_Limit& from) { CPUPowerRapl_Limit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CPUPowerRapl_Limit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.CPUPowerRapl.Limit"; }

  explicit CPUPowerRapl_Limit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CPUPowerRapl_Limit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CPUPowerRapl_Limit& from);
  CPUPowerRapl_Limit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CPUPowerRapl_Limit&& from) noexcept
      : CPUPowerRapl_Limit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 4,
    kMaxPowerUwFieldNumber = 1,
    kPowerLimitUwFieldNumber = 2,
    kTimeWindowUsFieldNumber = 3,
  };
  // string name = 4;
  bool has_name() const;
  void clear_name() ;
  ::absl::string_view name() const;
  template <typename Arg_ = ::std::string&&>
  void set_name(Arg_&& arg);

  private:
  ::absl::string_view _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(::absl::string_view value);

  public:
  // uint64 max_power_uw = 1;
  bool has_max_power_uw() const;
  void clear_max_power_uw() ;
  ::uint64_t max_power_uw() const;
  void set_max_power_uw(::uint64_t value);

  private:
  ::uint64_t _internal_max_power_uw() const;
  void _internal_set_max_power_uw(::uint64_t value);

  public:
  // uint64 power_limit_uw = 2;
  bool has_power_limit_uw() const;
  void clear_power_limit_uw() ;
  ::uint64_t power_limit_uw() const;
  void set_power_limit_uw(::uint64_t value);

  private:
  ::uint64_t _internal_power_limit_uw() const;
  void _internal_set_power_limit_uw(::uint64_t value);

  public:
  // uint64 time_window_us = 3;
  bool has_time_window_us() const;
  void clear_time_window_us() ;
  ::uint64_t time_window_us() const;
  void set_time_window_us(::uint64_t value);

  private:
  ::uint64_t _internal_time_window_us() const;
  void _internal_set_time_window_us(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.CPUPowerRapl.Limit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 47,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CPUPowerRapl_Limit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::uint64_t max_power_uw_;
    ::uint64_t power_limit_uw_;
    ::uint64_t time_window_us_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CpuPowerRapl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CPUPowerRapl_Limit_class_data_;
// -------------------------------------------------------------------

class CPUPowerRapl final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.CPUPowerRapl) */ {
 public:
  inline CPUPowerRapl() : CPUPowerRapl(nullptr) {}
  ~CPUPowerRapl() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CPUPowerRapl* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CPUPowerRapl));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CPUPowerRapl(::google::protobuf::internal::ConstantInitialized);

  inline CPUPowerRapl(const CPUPowerRapl& from) : CPUPowerRapl(nullptr, from) {}
  inline CPUPowerRapl(CPUPowerRapl&& from) noexcept
      : CPUPowerRapl(nullptr, ::std::move(from)) {}
  inline CPUPowerRapl& operator=(const CPUPowerRapl& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPUPowerRapl& operator=(CPUPowerRapl&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CPUPowerRapl& default_instance() {
    return *reinterpret_cast<const CPUPowerRapl*>(
        &_CPUPowerRapl_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CPUPowerRapl& a, CPUPowerRapl& b) { a.Swap(&b); }
  inline void Swap(CPUPowerRapl* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPUPowerRapl* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CPUPowerRapl* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CPUPowerRapl>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CPUPowerRapl& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CPUPowerRapl& from) { CPUPowerRapl::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CPUPowerRapl* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.CPUPowerRapl"; }

  explicit CPUPowerRapl(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CPUPowerRapl(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CPUPowerRapl& from);
  CPUPowerRapl(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CPUPowerRapl&& from) noexcept
      : CPUPowerRapl(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Limit = CPUPowerRapl_Limit;

  // accessors -------------------------------------------------------
  enum : int {
    kLtpLimitFieldNumber = 1,
    kStpLimitFieldNumber = 2,
    kPpLimitFieldNumber = 3,
  };
  // .legion.messages.CPUPowerRapl.Limit ltp_limit = 1;
  bool has_ltp_limit() const;
  void clear_ltp_limit() ;
  const ::legion::messages::CPUPowerRapl_Limit& ltp_limit() const;
  [[nodiscard]] ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE release_ltp_limit();
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL mutable_ltp_limit();
  void set_allocated_ltp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ltp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE unsafe_arena_release_ltp_limit();

  private:
  const ::legion::messages::CPUPowerRapl_Limit& _internal_ltp_limit() const;
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL _internal_mutable_ltp_limit();

  public:
  // .legion.messages.CPUPowerRapl.Limit stp_limit = 2;
  bool has_stp_limit() const;
  void clear_stp_limit() ;
  const ::legion::messages::CPUPowerRapl_Limit& stp_limit() const;
  [[nodiscard]] ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE release_stp_limit();
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL mutable_stp_limit();
  void set_allocated_stp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_stp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE unsafe_arena_release_stp_limit();

  private:
  const ::legion::messages::CPUPowerRapl_Limit& _internal_stp_limit() const;
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL _internal_mutable_stp_limit();

  public:
  // .legion.messages.CPUPowerRapl.Limit pp_limit = 3;
  bool has_pp_limit() const;
  void clear_pp_limit() ;
  const ::legion::messages::CPUPowerRapl_Limit& pp_limit() const;
  [[nodiscard]] ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE release_pp_limit();
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL mutable_pp_limit();
  void set_allocated_pp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_pp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE unsafe_arena_release_pp_limit();

  private:
  const ::legion::messages::CPUPowerRapl_Limit& _internal_pp_limit() const;
  ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL _internal_mutable_pp_limit();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.CPUPowerRapl)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CPUPowerRapl& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE ltp_limit_;
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE stp_limit_;
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE pp_limit_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CpuPowerRapl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CPUPowerRapl_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CPUPowerRapl_Limit

// uint64 max_power_uw = 1;
inline bool CPUPowerRapl_Limit::has_max_power_uw() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CPUPowerRapl_Limit::clear_max_power_uw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_power_uw_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t CPUPowerRapl_Limit::max_power_uw() const {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.Limit.max_power_uw)
  return _internal_max_power_uw();
}
inline void CPUPowerRapl_Limit::set_max_power_uw(::uint64_t value) {
  _internal_set_max_power_uw(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.CPUPowerRapl.Limit.max_power_uw)
}
inline ::uint64_t CPUPowerRapl_Limit::_internal_max_power_uw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_power_uw_;
}
inline void CPUPowerRapl_Limit::_internal_set_max_power_uw(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_power_uw_ = value;
}

// uint64 power_limit_uw = 2;
inline bool CPUPowerRapl_Limit::has_power_limit_uw() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CPUPowerRapl_Limit::clear_power_limit_uw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_limit_uw_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t CPUPowerRapl_Limit::power_limit_uw() const {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.Limit.power_limit_uw)
  return _internal_power_limit_uw();
}
inline void CPUPowerRapl_Limit::set_power_limit_uw(::uint64_t value) {
  _internal_set_power_limit_uw(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:legion.messages.CPUPowerRapl.Limit.power_limit_uw)
}
inline ::uint64_t CPUPowerRapl_Limit::_internal_power_limit_uw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.power_limit_uw_;
}
inline void CPUPowerRapl_Limit::_internal_set_power_limit_uw(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_limit_uw_ = value;
}

// uint64 time_window_us = 3;
inline bool CPUPowerRapl_Limit::has_time_window_us() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CPUPowerRapl_Limit::clear_time_window_us() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_window_us_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t CPUPowerRapl_Limit::time_window_us() const {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.Limit.time_window_us)
  return _internal_time_window_us();
}
inline void CPUPowerRapl_Limit::set_time_window_us(::uint64_t value) {
  _internal_set_time_window_us(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:legion.messages.CPUPowerRapl.Limit.time_window_us)
}
inline ::uint64_t CPUPowerRapl_Limit::_internal_time_window_us() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_window_us_;
}
inline void CPUPowerRapl_Limit::_internal_set_time_window_us(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_window_us_ = value;
}

// string name = 4;
inline bool CPUPowerRapl_Limit::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CPUPowerRapl_Limit::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view CPUPowerRapl_Limit::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.Limit.name)
  return _internal_name();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CPUPowerRapl_Limit::set_name(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:legion.messages.CPUPowerRapl.Limit.name)
}
inline ::absl::string_view CPUPowerRapl_Limit::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void CPUPowerRapl_Limit::_internal_set_name(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// CPUPowerRapl

// .legion.messages.CPUPowerRapl.Limit ltp_limit = 1;
inline bool CPUPowerRapl::has_ltp_limit() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.ltp_limit_ != nullptr);
  return value;
}
inline void CPUPowerRapl::clear_ltp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ltp_limit_ != nullptr) _impl_.ltp_limit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::_internal_ltp_limit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::CPUPowerRapl_Limit* p = _impl_.ltp_limit_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::CPUPowerRapl_Limit&>(::legion::messages::_CPUPowerRapl_Limit_default_instance_);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::ltp_limit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.ltp_limit)
  return _internal_ltp_limit();
}
inline void CPUPowerRapl::unsafe_arena_set_allocated_ltp_limit(
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ltp_limit_);
  }
  _impl_.ltp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.CPUPowerRapl.ltp_limit)
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::release_ltp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::CPUPowerRapl_Limit* released = _impl_.ltp_limit_;
  _impl_.ltp_limit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::unsafe_arena_release_ltp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.CPUPowerRapl.ltp_limit)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::CPUPowerRapl_Limit* temp = _impl_.ltp_limit_;
  _impl_.ltp_limit_ = nullptr;
  return temp;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::_internal_mutable_ltp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ltp_limit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::CPUPowerRapl_Limit>(GetArena());
    _impl_.ltp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(p);
  }
  return _impl_.ltp_limit_;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::mutable_ltp_limit()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::CPUPowerRapl_Limit* _msg = _internal_mutable_ltp_limit();
  // @@protoc_insertion_point(field_mutable:legion.messages.CPUPowerRapl.ltp_limit)
  return _msg;
}
inline void CPUPowerRapl::set_allocated_ltp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ltp_limit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.ltp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.CPUPowerRapl.ltp_limit)
}

// .legion.messages.CPUPowerRapl.Limit stp_limit = 2;
inline bool CPUPowerRapl::has_stp_limit() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.stp_limit_ != nullptr);
  return value;
}
inline void CPUPowerRapl::clear_stp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.stp_limit_ != nullptr) _impl_.stp_limit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::_internal_stp_limit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::CPUPowerRapl_Limit* p = _impl_.stp_limit_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::CPUPowerRapl_Limit&>(::legion::messages::_CPUPowerRapl_Limit_default_instance_);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::stp_limit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.stp_limit)
  return _internal_stp_limit();
}
inline void CPUPowerRapl::unsafe_arena_set_allocated_stp_limit(
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.stp_limit_);
  }
  _impl_.stp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.CPUPowerRapl.stp_limit)
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::release_stp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::CPUPowerRapl_Limit* released = _impl_.stp_limit_;
  _impl_.stp_limit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::unsafe_arena_release_stp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.CPUPowerRapl.stp_limit)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::CPUPowerRapl_Limit* temp = _impl_.stp_limit_;
  _impl_.stp_limit_ = nullptr;
  return temp;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::_internal_mutable_stp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.stp_limit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::CPUPowerRapl_Limit>(GetArena());
    _impl_.stp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(p);
  }
  return _impl_.stp_limit_;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::mutable_stp_limit()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::CPUPowerRapl_Limit* _msg = _internal_mutable_stp_limit();
  // @@protoc_insertion_point(field_mutable:legion.messages.CPUPowerRapl.stp_limit)
  return _msg;
}
inline void CPUPowerRapl::set_allocated_stp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.stp_limit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.stp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.CPUPowerRapl.stp_limit)
}

// .legion.messages.CPUPowerRapl.Limit pp_limit = 3;
inline bool CPUPowerRapl::has_pp_limit() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.pp_limit_ != nullptr);
  return value;
}
inline void CPUPowerRapl::clear_pp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pp_limit_ != nullptr) _impl_.pp_limit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::_internal_pp_limit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::CPUPowerRapl_Limit* p = _impl_.pp_limit_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::CPUPowerRapl_Limit&>(::legion::messages::_CPUPowerRapl_Limit_default_instance_);
}
inline const ::legion::messages::CPUPowerRapl_Limit& CPUPowerRapl::pp_limit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.CPUPowerRapl.pp_limit)
  return _internal_pp_limit();
}
inline void CPUPowerRapl::unsafe_arena_set_allocated_pp_limit(
    ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pp_limit_);
  }
  _impl_.pp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.CPUPowerRapl.pp_limit)
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::release_pp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::CPUPowerRapl_Limit* released = _impl_.pp_limit_;
  _impl_.pp_limit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE CPUPowerRapl::unsafe_arena_release_pp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.CPUPowerRapl.pp_limit)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::CPUPowerRapl_Limit* temp = _impl_.pp_limit_;
  _impl_.pp_limit_ = nullptr;
  return temp;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::_internal_mutable_pp_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pp_limit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::CPUPowerRapl_Limit>(GetArena());
    _impl_.pp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(p);
  }
  return _impl_.pp_limit_;
}
inline ::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NONNULL CPUPowerRapl::mutable_pp_limit()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::CPUPowerRapl_Limit* _msg = _internal_mutable_pp_limit();
  // @@protoc_insertion_point(field_mutable:legion.messages.CPUPowerRapl.pp_limit)
  return _msg;
}
inline void CPUPowerRapl::set_allocated_pp_limit(::legion::messages::CPUPowerRapl_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pp_limit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.pp_limit_ = reinterpret_cast<::legion::messages::CPUPowerRapl_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.CPUPowerRapl.pp_limit)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // CpuPowerRapl_2eproto_2epb_2eh
