// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FanControl.proto
// Protobuf C++ Version: 6.33.1

#ifndef FanControl_2eproto_2epb_2eh
#define FanControl_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FanControl_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_FanControl_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_FanControl_2eproto;
}  // extern "C"
namespace legion {
namespace messages {
class FanCurve;
struct FanCurveDefaultTypeInternal;
extern FanCurveDefaultTypeInternal _FanCurve_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_class_data_;
class FanCurve_CpuDefaultEntry_DoNotUse;
struct FanCurve_CpuDefaultEntry_DoNotUseDefaultTypeInternal;
extern FanCurve_CpuDefaultEntry_DoNotUseDefaultTypeInternal _FanCurve_CpuDefaultEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_CpuDefaultEntry_DoNotUse_class_data_;
class FanCurve_CpusenDefaultEntry_DoNotUse;
struct FanCurve_CpusenDefaultEntry_DoNotUseDefaultTypeInternal;
extern FanCurve_CpusenDefaultEntry_DoNotUseDefaultTypeInternal _FanCurve_CpusenDefaultEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_CpusenDefaultEntry_DoNotUse_class_data_;
class FanCurve_Default;
struct FanCurve_DefaultDefaultTypeInternal;
extern FanCurve_DefaultDefaultTypeInternal _FanCurve_Default_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_Default_class_data_;
class FanCurve_Gpu2DefaultEntry_DoNotUse;
struct FanCurve_Gpu2DefaultEntry_DoNotUseDefaultTypeInternal;
extern FanCurve_Gpu2DefaultEntry_DoNotUseDefaultTypeInternal _FanCurve_Gpu2DefaultEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_Gpu2DefaultEntry_DoNotUse_class_data_;
class FanCurve_GpuDefaultEntry_DoNotUse;
struct FanCurve_GpuDefaultEntry_DoNotUseDefaultTypeInternal;
extern FanCurve_GpuDefaultEntry_DoNotUseDefaultTypeInternal _FanCurve_GpuDefaultEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_GpuDefaultEntry_DoNotUse_class_data_;
class FanCurve_Points;
struct FanCurve_PointsDefaultTypeInternal;
extern FanCurve_PointsDefaultTypeInternal _FanCurve_Points_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanCurve_Points_class_data_;
class FanOption;
struct FanOptionDefaultTypeInternal;
extern FanOptionDefaultTypeInternal _FanOption_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FanOption_class_data_;
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace legion {
namespace messages {

// ===================================================================


// -------------------------------------------------------------------

class FanOption final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.FanOption) */ {
 public:
  inline FanOption() : FanOption(nullptr) {}
  ~FanOption() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FanOption* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FanOption));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanOption(::google::protobuf::internal::ConstantInitialized);

  inline FanOption(const FanOption& from) : FanOption(nullptr, from) {}
  inline FanOption(FanOption&& from) noexcept
      : FanOption(nullptr, ::std::move(from)) {}
  inline FanOption& operator=(const FanOption& from) {
    CopyFrom(from);
    return *this;
  }
  inline FanOption& operator=(FanOption&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FanOption& default_instance() {
    return *reinterpret_cast<const FanOption*>(
        &_FanOption_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FanOption& a, FanOption& b) { a.Swap(&b); }
  inline void Swap(FanOption* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FanOption* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FanOption* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FanOption>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FanOption& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FanOption& from) { FanOption::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FanOption* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.FanOption"; }

  explicit FanOption(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FanOption(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FanOption& from);
  FanOption(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FanOption&& from) noexcept
      : FanOption(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFullSpeedFieldNumber = 1,
    kLockFieldNumber = 2,
  };
  // bool full_speed = 1;
  bool has_full_speed() const;
  void clear_full_speed() ;
  bool full_speed() const;
  void set_full_speed(bool value);

  private:
  bool _internal_full_speed() const;
  void _internal_set_full_speed(bool value);

  public:
  // bool lock = 2;
  bool has_lock() const;
  void clear_lock() ;
  bool lock() const;
  void set_lock(bool value);

  private:
  bool _internal_lock() const;
  void _internal_set_lock(bool value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.FanOption)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FanOption& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool full_speed_;
    bool lock_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FanControl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FanOption_class_data_;
// -------------------------------------------------------------------

class FanCurve_Points final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.FanCurve.Points) */ {
 public:
  inline FanCurve_Points() : FanCurve_Points(nullptr) {}
  ~FanCurve_Points() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FanCurve_Points* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FanCurve_Points));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_Points(::google::protobuf::internal::ConstantInitialized);

  inline FanCurve_Points(const FanCurve_Points& from) : FanCurve_Points(nullptr, from) {}
  inline FanCurve_Points(FanCurve_Points&& from) noexcept
      : FanCurve_Points(nullptr, ::std::move(from)) {}
  inline FanCurve_Points& operator=(const FanCurve_Points& from) {
    CopyFrom(from);
    return *this;
  }
  inline FanCurve_Points& operator=(FanCurve_Points&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FanCurve_Points& default_instance() {
    return *reinterpret_cast<const FanCurve_Points*>(
        &_FanCurve_Points_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FanCurve_Points& a, FanCurve_Points& b) { a.Swap(&b); }
  inline void Swap(FanCurve_Points* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FanCurve_Points* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FanCurve_Points* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FanCurve_Points>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FanCurve_Points& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FanCurve_Points& from) { FanCurve_Points::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FanCurve_Points* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.FanCurve.Points"; }

  explicit FanCurve_Points(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FanCurve_Points(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FanCurve_Points& from);
  FanCurve_Points(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FanCurve_Points&& from) noexcept
      : FanCurve_Points(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoint1FieldNumber = 1,
    kPoint2FieldNumber = 2,
    kPoint3FieldNumber = 3,
    kPoint4FieldNumber = 4,
    kPoint5FieldNumber = 5,
    kPoint6FieldNumber = 6,
    kPoint7FieldNumber = 7,
    kPoint8FieldNumber = 8,
    kPoint9FieldNumber = 9,
    kPoint10FieldNumber = 10,
  };
  // uint32 point1 = 1;
  bool has_point1() const;
  void clear_point1() ;
  ::uint32_t point1() const;
  void set_point1(::uint32_t value);

  private:
  ::uint32_t _internal_point1() const;
  void _internal_set_point1(::uint32_t value);

  public:
  // uint32 point2 = 2;
  bool has_point2() const;
  void clear_point2() ;
  ::uint32_t point2() const;
  void set_point2(::uint32_t value);

  private:
  ::uint32_t _internal_point2() const;
  void _internal_set_point2(::uint32_t value);

  public:
  // uint32 point3 = 3;
  bool has_point3() const;
  void clear_point3() ;
  ::uint32_t point3() const;
  void set_point3(::uint32_t value);

  private:
  ::uint32_t _internal_point3() const;
  void _internal_set_point3(::uint32_t value);

  public:
  // uint32 point4 = 4;
  bool has_point4() const;
  void clear_point4() ;
  ::uint32_t point4() const;
  void set_point4(::uint32_t value);

  private:
  ::uint32_t _internal_point4() const;
  void _internal_set_point4(::uint32_t value);

  public:
  // uint32 point5 = 5;
  bool has_point5() const;
  void clear_point5() ;
  ::uint32_t point5() const;
  void set_point5(::uint32_t value);

  private:
  ::uint32_t _internal_point5() const;
  void _internal_set_point5(::uint32_t value);

  public:
  // uint32 point6 = 6;
  bool has_point6() const;
  void clear_point6() ;
  ::uint32_t point6() const;
  void set_point6(::uint32_t value);

  private:
  ::uint32_t _internal_point6() const;
  void _internal_set_point6(::uint32_t value);

  public:
  // uint32 point7 = 7;
  bool has_point7() const;
  void clear_point7() ;
  ::uint32_t point7() const;
  void set_point7(::uint32_t value);

  private:
  ::uint32_t _internal_point7() const;
  void _internal_set_point7(::uint32_t value);

  public:
  // uint32 point8 = 8;
  bool has_point8() const;
  void clear_point8() ;
  ::uint32_t point8() const;
  void set_point8(::uint32_t value);

  private:
  ::uint32_t _internal_point8() const;
  void _internal_set_point8(::uint32_t value);

  public:
  // uint32 point9 = 9;
  bool has_point9() const;
  void clear_point9() ;
  ::uint32_t point9() const;
  void set_point9(::uint32_t value);

  private:
  ::uint32_t _internal_point9() const;
  void _internal_set_point9(::uint32_t value);

  public:
  // uint32 point10 = 10;
  bool has_point10() const;
  void clear_point10() ;
  ::uint32_t point10() const;
  void set_point10(::uint32_t value);

  private:
  ::uint32_t _internal_point10() const;
  void _internal_set_point10(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.FanCurve.Points)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FanCurve_Points& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t point1_;
    ::uint32_t point2_;
    ::uint32_t point3_;
    ::uint32_t point4_;
    ::uint32_t point5_;
    ::uint32_t point6_;
    ::uint32_t point7_;
    ::uint32_t point8_;
    ::uint32_t point9_;
    ::uint32_t point10_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FanControl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FanCurve_Points_class_data_;
// -------------------------------------------------------------------

class FanCurve_Default final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.FanCurve.Default) */ {
 public:
  inline FanCurve_Default() : FanCurve_Default(nullptr) {}
  ~FanCurve_Default() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FanCurve_Default* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FanCurve_Default));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_Default(::google::protobuf::internal::ConstantInitialized);

  inline FanCurve_Default(const FanCurve_Default& from) : FanCurve_Default(nullptr, from) {}
  inline FanCurve_Default(FanCurve_Default&& from) noexcept
      : FanCurve_Default(nullptr, ::std::move(from)) {}
  inline FanCurve_Default& operator=(const FanCurve_Default& from) {
    CopyFrom(from);
    return *this;
  }
  inline FanCurve_Default& operator=(FanCurve_Default&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FanCurve_Default& default_instance() {
    return *reinterpret_cast<const FanCurve_Default*>(
        &_FanCurve_Default_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FanCurve_Default& a, FanCurve_Default& b) { a.Swap(&b); }
  inline void Swap(FanCurve_Default* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FanCurve_Default* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FanCurve_Default* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FanCurve_Default>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FanCurve_Default& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FanCurve_Default& from) { FanCurve_Default::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FanCurve_Default* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.FanCurve.Default"; }

  explicit FanCurve_Default(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FanCurve_Default(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FanCurve_Default& from);
  FanCurve_Default(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FanCurve_Default&& from) noexcept
      : FanCurve_Default(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFanFieldNumber = 1,
    kSensorsFieldNumber = 2,
  };
  // repeated uint32 fan = 1;
  int fan_size() const;
  private:
  int _internal_fan_size() const;

  public:
  void clear_fan() ;
  ::uint32_t fan(int index) const;
  void set_fan(int index, ::uint32_t value);
  void add_fan(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& fan() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_fan();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_fan() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_fan();

  public:
  // repeated uint32 sensors = 2;
  int sensors_size() const;
  private:
  int _internal_sensors_size() const;

  public:
  void clear_sensors() ;
  ::uint32_t sensors(int index) const;
  void set_sensors(int index, ::uint32_t value);
  void add_sensors(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& sensors() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_sensors();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_sensors() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_sensors();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.FanCurve.Default)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FanCurve_Default& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> fan_;
    ::google::protobuf::internal::CachedSize _fan_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> sensors_;
    ::google::protobuf::internal::CachedSize _sensors_cached_byte_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FanControl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FanCurve_Default_class_data_;
// -------------------------------------------------------------------

class FanCurve_GpuDefaultEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  FanCurve_GpuDefaultEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_GpuDefaultEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit FanCurve_GpuDefaultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_FanCurve_GpuDefaultEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_FanControl_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull FanCurve_GpuDefaultEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class FanCurve_Gpu2DefaultEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  FanCurve_Gpu2DefaultEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_Gpu2DefaultEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit FanCurve_Gpu2DefaultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_FanCurve_Gpu2DefaultEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_FanControl_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull FanCurve_Gpu2DefaultEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class FanCurve_CpusenDefaultEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  FanCurve_CpusenDefaultEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_CpusenDefaultEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit FanCurve_CpusenDefaultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_FanCurve_CpusenDefaultEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_FanControl_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull FanCurve_CpusenDefaultEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class FanCurve_CpuDefaultEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::uint32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  FanCurve_CpuDefaultEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve_CpuDefaultEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit FanCurve_CpuDefaultEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_FanCurve_CpuDefaultEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_FanControl_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull FanCurve_CpuDefaultEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class FanCurve final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.FanCurve) */ {
 public:
  inline FanCurve() : FanCurve(nullptr) {}
  ~FanCurve() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FanCurve* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FanCurve));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FanCurve(::google::protobuf::internal::ConstantInitialized);

  inline FanCurve(const FanCurve& from) : FanCurve(nullptr, from) {}
  inline FanCurve(FanCurve&& from) noexcept
      : FanCurve(nullptr, ::std::move(from)) {}
  inline FanCurve& operator=(const FanCurve& from) {
    CopyFrom(from);
    return *this;
  }
  inline FanCurve& operator=(FanCurve&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FanCurve& default_instance() {
    return *reinterpret_cast<const FanCurve*>(
        &_FanCurve_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(FanCurve& a, FanCurve& b) { a.Swap(&b); }
  inline void Swap(FanCurve* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FanCurve* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FanCurve* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FanCurve>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FanCurve& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FanCurve& from) { FanCurve::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FanCurve* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.FanCurve"; }

  explicit FanCurve(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FanCurve(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FanCurve& from);
  FanCurve(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FanCurve&& from) noexcept
      : FanCurve(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Points = FanCurve_Points;
  using Default = FanCurve_Default;

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentValueFieldNumber = 1,
    kCpuDefaultFieldNumber = 2,
    kCpusenDefaultFieldNumber = 3,
    kGpuDefaultFieldNumber = 4,
    kGpu2DefaultFieldNumber = 5,
  };
  // .legion.messages.FanCurve.Points current_value = 1;
  bool has_current_value() const;
  void clear_current_value() ;
  const ::legion::messages::FanCurve_Points& current_value() const;
  [[nodiscard]] ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE release_current_value();
  ::legion::messages::FanCurve_Points* PROTOBUF_NONNULL mutable_current_value();
  void set_allocated_current_value(::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_current_value(::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE value);
  ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE unsafe_arena_release_current_value();

  private:
  const ::legion::messages::FanCurve_Points& _internal_current_value() const;
  ::legion::messages::FanCurve_Points* PROTOBUF_NONNULL _internal_mutable_current_value();

  public:
  // map<uint32, .legion.messages.FanCurve.Default> cpu_default = 2;
  int cpu_default_size() const;
  private:
  int _internal_cpu_default_size() const;

  public:
  void clear_cpu_default() ;
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& cpu_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL mutable_cpu_default();

  private:
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& _internal_cpu_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL _internal_mutable_cpu_default();

  public:
  // map<uint32, .legion.messages.FanCurve.Default> cpusen_default = 3;
  int cpusen_default_size() const;
  private:
  int _internal_cpusen_default_size() const;

  public:
  void clear_cpusen_default() ;
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& cpusen_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL mutable_cpusen_default();

  private:
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& _internal_cpusen_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL _internal_mutable_cpusen_default();

  public:
  // map<uint32, .legion.messages.FanCurve.Default> gpu_default = 4;
  int gpu_default_size() const;
  private:
  int _internal_gpu_default_size() const;

  public:
  void clear_gpu_default() ;
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& gpu_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL mutable_gpu_default();

  private:
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& _internal_gpu_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL _internal_mutable_gpu_default();

  public:
  // map<uint32, .legion.messages.FanCurve.Default> gpu2_default = 5;
  int gpu2_default_size() const;
  private:
  int _internal_gpu2_default_size() const;

  public:
  void clear_gpu2_default() ;
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& gpu2_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL mutable_gpu2_default();

  private:
  const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& _internal_gpu2_default() const;
  ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL _internal_mutable_gpu2_default();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.FanCurve)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 5,
                                   9, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FanCurve& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE current_value_;
    ::google::protobuf::internal::MapField<FanCurve_CpuDefaultEntry_DoNotUse, ::uint32_t, ::legion::messages::FanCurve_Default,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        cpu_default_;
    ::google::protobuf::internal::MapField<FanCurve_CpusenDefaultEntry_DoNotUse, ::uint32_t, ::legion::messages::FanCurve_Default,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        cpusen_default_;
    ::google::protobuf::internal::MapField<FanCurve_GpuDefaultEntry_DoNotUse, ::uint32_t, ::legion::messages::FanCurve_Default,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        gpu_default_;
    ::google::protobuf::internal::MapField<FanCurve_Gpu2DefaultEntry_DoNotUse, ::uint32_t, ::legion::messages::FanCurve_Default,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        gpu2_default_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FanControl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FanCurve_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FanOption

// bool full_speed = 1;
inline bool FanOption::has_full_speed() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void FanOption::clear_full_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.full_speed_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool FanOption::full_speed() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanOption.full_speed)
  return _internal_full_speed();
}
inline void FanOption::set_full_speed(bool value) {
  _internal_set_full_speed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.FanOption.full_speed)
}
inline bool FanOption::_internal_full_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.full_speed_;
}
inline void FanOption::_internal_set_full_speed(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.full_speed_ = value;
}

// bool lock = 2;
inline bool FanOption::has_lock() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void FanOption::clear_lock() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lock_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool FanOption::lock() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanOption.lock)
  return _internal_lock();
}
inline void FanOption::set_lock(bool value) {
  _internal_set_lock(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.FanOption.lock)
}
inline bool FanOption::_internal_lock() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lock_;
}
inline void FanOption::_internal_set_lock(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lock_ = value;
}

// -------------------------------------------------------------------

// FanCurve_Points

// uint32 point1 = 1;
inline bool FanCurve_Points::has_point1() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void FanCurve_Points::clear_point1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point1_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t FanCurve_Points::point1() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point1)
  return _internal_point1();
}
inline void FanCurve_Points::set_point1(::uint32_t value) {
  _internal_set_point1(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point1)
}
inline ::uint32_t FanCurve_Points::_internal_point1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point1_;
}
inline void FanCurve_Points::_internal_set_point1(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point1_ = value;
}

// uint32 point2 = 2;
inline bool FanCurve_Points::has_point2() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void FanCurve_Points::clear_point2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point2_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t FanCurve_Points::point2() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point2)
  return _internal_point2();
}
inline void FanCurve_Points::set_point2(::uint32_t value) {
  _internal_set_point2(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point2)
}
inline ::uint32_t FanCurve_Points::_internal_point2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point2_;
}
inline void FanCurve_Points::_internal_set_point2(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point2_ = value;
}

// uint32 point3 = 3;
inline bool FanCurve_Points::has_point3() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void FanCurve_Points::clear_point3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point3_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t FanCurve_Points::point3() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point3)
  return _internal_point3();
}
inline void FanCurve_Points::set_point3(::uint32_t value) {
  _internal_set_point3(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point3)
}
inline ::uint32_t FanCurve_Points::_internal_point3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point3_;
}
inline void FanCurve_Points::_internal_set_point3(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point3_ = value;
}

// uint32 point4 = 4;
inline bool FanCurve_Points::has_point4() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void FanCurve_Points::clear_point4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point4_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t FanCurve_Points::point4() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point4)
  return _internal_point4();
}
inline void FanCurve_Points::set_point4(::uint32_t value) {
  _internal_set_point4(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point4)
}
inline ::uint32_t FanCurve_Points::_internal_point4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point4_;
}
inline void FanCurve_Points::_internal_set_point4(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point4_ = value;
}

// uint32 point5 = 5;
inline bool FanCurve_Points::has_point5() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void FanCurve_Points::clear_point5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point5_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t FanCurve_Points::point5() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point5)
  return _internal_point5();
}
inline void FanCurve_Points::set_point5(::uint32_t value) {
  _internal_set_point5(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point5)
}
inline ::uint32_t FanCurve_Points::_internal_point5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point5_;
}
inline void FanCurve_Points::_internal_set_point5(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point5_ = value;
}

// uint32 point6 = 6;
inline bool FanCurve_Points::has_point6() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void FanCurve_Points::clear_point6() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point6_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t FanCurve_Points::point6() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point6)
  return _internal_point6();
}
inline void FanCurve_Points::set_point6(::uint32_t value) {
  _internal_set_point6(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point6)
}
inline ::uint32_t FanCurve_Points::_internal_point6() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point6_;
}
inline void FanCurve_Points::_internal_set_point6(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point6_ = value;
}

// uint32 point7 = 7;
inline bool FanCurve_Points::has_point7() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void FanCurve_Points::clear_point7() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point7_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t FanCurve_Points::point7() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point7)
  return _internal_point7();
}
inline void FanCurve_Points::set_point7(::uint32_t value) {
  _internal_set_point7(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point7)
}
inline ::uint32_t FanCurve_Points::_internal_point7() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point7_;
}
inline void FanCurve_Points::_internal_set_point7(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point7_ = value;
}

// uint32 point8 = 8;
inline bool FanCurve_Points::has_point8() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void FanCurve_Points::clear_point8() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point8_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::uint32_t FanCurve_Points::point8() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point8)
  return _internal_point8();
}
inline void FanCurve_Points::set_point8(::uint32_t value) {
  _internal_set_point8(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point8)
}
inline ::uint32_t FanCurve_Points::_internal_point8() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point8_;
}
inline void FanCurve_Points::_internal_set_point8(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point8_ = value;
}

// uint32 point9 = 9;
inline bool FanCurve_Points::has_point9() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void FanCurve_Points::clear_point9() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point9_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint32_t FanCurve_Points::point9() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point9)
  return _internal_point9();
}
inline void FanCurve_Points::set_point9(::uint32_t value) {
  _internal_set_point9(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point9)
}
inline ::uint32_t FanCurve_Points::_internal_point9() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point9_;
}
inline void FanCurve_Points::_internal_set_point9(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point9_ = value;
}

// uint32 point10 = 10;
inline bool FanCurve_Points::has_point10() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void FanCurve_Points::clear_point10() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point10_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint32_t FanCurve_Points::point10() const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Points.point10)
  return _internal_point10();
}
inline void FanCurve_Points::set_point10(::uint32_t value) {
  _internal_set_point10(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Points.point10)
}
inline ::uint32_t FanCurve_Points::_internal_point10() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point10_;
}
inline void FanCurve_Points::_internal_set_point10(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point10_ = value;
}

// -------------------------------------------------------------------

// FanCurve_Default

// repeated uint32 fan = 1;
inline int FanCurve_Default::_internal_fan_size() const {
  return _internal_fan().size();
}
inline int FanCurve_Default::fan_size() const {
  return _internal_fan_size();
}
inline void FanCurve_Default::clear_fan() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t FanCurve_Default::fan(int index) const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Default.fan)
  return _internal_fan().Get(index);
}
inline void FanCurve_Default::set_fan(int index, ::uint32_t value) {
  _internal_mutable_fan()->Set(index, value);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Default.fan)
}
inline void FanCurve_Default::add_fan(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_fan()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:legion.messages.FanCurve.Default.fan)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& FanCurve_Default::fan() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:legion.messages.FanCurve.Default.fan)
  return _internal_fan();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL FanCurve_Default::mutable_fan()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:legion.messages.FanCurve.Default.fan)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_fan();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
FanCurve_Default::_internal_fan() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fan_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
FanCurve_Default::_internal_mutable_fan() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.fan_;
}

// repeated uint32 sensors = 2;
inline int FanCurve_Default::_internal_sensors_size() const {
  return _internal_sensors().size();
}
inline int FanCurve_Default::sensors_size() const {
  return _internal_sensors_size();
}
inline void FanCurve_Default::clear_sensors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sensors_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t FanCurve_Default::sensors(int index) const {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.Default.sensors)
  return _internal_sensors().Get(index);
}
inline void FanCurve_Default::set_sensors(int index, ::uint32_t value) {
  _internal_mutable_sensors()->Set(index, value);
  // @@protoc_insertion_point(field_set:legion.messages.FanCurve.Default.sensors)
}
inline void FanCurve_Default::add_sensors(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_sensors()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:legion.messages.FanCurve.Default.sensors)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& FanCurve_Default::sensors() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:legion.messages.FanCurve.Default.sensors)
  return _internal_sensors();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL FanCurve_Default::mutable_sensors()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:legion.messages.FanCurve.Default.sensors)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_sensors();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
FanCurve_Default::_internal_sensors() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sensors_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
FanCurve_Default::_internal_mutable_sensors() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.sensors_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// FanCurve

// .legion.messages.FanCurve.Points current_value = 1;
inline bool FanCurve::has_current_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.current_value_ != nullptr);
  return value;
}
inline void FanCurve::clear_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.current_value_ != nullptr) _impl_.current_value_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::legion::messages::FanCurve_Points& FanCurve::_internal_current_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::FanCurve_Points* p = _impl_.current_value_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::FanCurve_Points&>(::legion::messages::_FanCurve_Points_default_instance_);
}
inline const ::legion::messages::FanCurve_Points& FanCurve::current_value() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.FanCurve.current_value)
  return _internal_current_value();
}
inline void FanCurve::unsafe_arena_set_allocated_current_value(
    ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.current_value_);
  }
  _impl_.current_value_ = reinterpret_cast<::legion::messages::FanCurve_Points*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.FanCurve.current_value)
}
inline ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE FanCurve::release_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::FanCurve_Points* released = _impl_.current_value_;
  _impl_.current_value_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE FanCurve::unsafe_arena_release_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.FanCurve.current_value)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::FanCurve_Points* temp = _impl_.current_value_;
  _impl_.current_value_ = nullptr;
  return temp;
}
inline ::legion::messages::FanCurve_Points* PROTOBUF_NONNULL FanCurve::_internal_mutable_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.current_value_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::FanCurve_Points>(GetArena());
    _impl_.current_value_ = reinterpret_cast<::legion::messages::FanCurve_Points*>(p);
  }
  return _impl_.current_value_;
}
inline ::legion::messages::FanCurve_Points* PROTOBUF_NONNULL FanCurve::mutable_current_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::FanCurve_Points* _msg = _internal_mutable_current_value();
  // @@protoc_insertion_point(field_mutable:legion.messages.FanCurve.current_value)
  return _msg;
}
inline void FanCurve::set_allocated_current_value(::legion::messages::FanCurve_Points* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.current_value_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.current_value_ = reinterpret_cast<::legion::messages::FanCurve_Points*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.FanCurve.current_value)
}

// map<uint32, .legion.messages.FanCurve.Default> cpu_default = 2;
inline int FanCurve::_internal_cpu_default_size() const {
  return _internal_cpu_default().size();
}
inline int FanCurve::cpu_default_size() const {
  return _internal_cpu_default_size();
}
inline void FanCurve::clear_cpu_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_default_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::_internal_cpu_default() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_default_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::cpu_default() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:legion.messages.FanCurve.cpu_default)
  return _internal_cpu_default();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::_internal_mutable_cpu_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cpu_default_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::mutable_cpu_default()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_map:legion.messages.FanCurve.cpu_default)
  return _internal_mutable_cpu_default();
}

// map<uint32, .legion.messages.FanCurve.Default> cpusen_default = 3;
inline int FanCurve::_internal_cpusen_default_size() const {
  return _internal_cpusen_default().size();
}
inline int FanCurve::cpusen_default_size() const {
  return _internal_cpusen_default_size();
}
inline void FanCurve::clear_cpusen_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpusen_default_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::_internal_cpusen_default() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpusen_default_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::cpusen_default() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:legion.messages.FanCurve.cpusen_default)
  return _internal_cpusen_default();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::_internal_mutable_cpusen_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cpusen_default_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::mutable_cpusen_default()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_map:legion.messages.FanCurve.cpusen_default)
  return _internal_mutable_cpusen_default();
}

// map<uint32, .legion.messages.FanCurve.Default> gpu_default = 4;
inline int FanCurve::_internal_gpu_default_size() const {
  return _internal_gpu_default().size();
}
inline int FanCurve::gpu_default_size() const {
  return _internal_gpu_default_size();
}
inline void FanCurve::clear_gpu_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpu_default_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::_internal_gpu_default() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpu_default_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::gpu_default() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:legion.messages.FanCurve.gpu_default)
  return _internal_gpu_default();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::_internal_mutable_gpu_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.gpu_default_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::mutable_gpu_default()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_map:legion.messages.FanCurve.gpu_default)
  return _internal_mutable_gpu_default();
}

// map<uint32, .legion.messages.FanCurve.Default> gpu2_default = 5;
inline int FanCurve::_internal_gpu2_default_size() const {
  return _internal_gpu2_default().size();
}
inline int FanCurve::gpu2_default_size() const {
  return _internal_gpu2_default_size();
}
inline void FanCurve::clear_gpu2_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpu2_default_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::_internal_gpu2_default() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpu2_default_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>& FanCurve::gpu2_default() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:legion.messages.FanCurve.gpu2_default)
  return _internal_gpu2_default();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::_internal_mutable_gpu2_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.gpu2_default_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::legion::messages::FanCurve_Default>* PROTOBUF_NONNULL FanCurve::mutable_gpu2_default()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_map:legion.messages.FanCurve.gpu2_default)
  return _internal_mutable_gpu2_default();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // FanControl_2eproto_2epb_2eh
