// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GPUPower.proto
// Protobuf C++ Version: 6.33.1

#ifndef GPUPower_2eproto_2epb_2eh
#define GPUPower_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_GPUPower_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_GPUPower_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_GPUPower_2eproto;
}  // extern "C"
namespace legion {
namespace messages {
class GPUPower;
struct GPUPowerDefaultTypeInternal;
extern GPUPowerDefaultTypeInternal _GPUPower_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GPUPower_class_data_;
class GPUPower_Limit;
struct GPUPower_LimitDefaultTypeInternal;
extern GPUPower_LimitDefaultTypeInternal _GPUPower_Limit_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_class_data_;
class GPUPower_Limit_Descriptor;
struct GPUPower_Limit_DescriptorDefaultTypeInternal;
extern GPUPower_Limit_DescriptorDefaultTypeInternal _GPUPower_Limit_Descriptor_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_Descriptor_class_data_;
class GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse;
struct GPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal;
extern GPUPower_Limit_ModeDescriptorMapEntry_DoNotUseDefaultTypeInternal _GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_;
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace legion {
namespace messages {

// ===================================================================


// -------------------------------------------------------------------

class GPUPower_Limit_Descriptor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.GPUPower.Limit.Descriptor) */ {
 public:
  inline GPUPower_Limit_Descriptor() : GPUPower_Limit_Descriptor(nullptr) {}
  ~GPUPower_Limit_Descriptor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GPUPower_Limit_Descriptor* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GPUPower_Limit_Descriptor));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GPUPower_Limit_Descriptor(::google::protobuf::internal::ConstantInitialized);

  inline GPUPower_Limit_Descriptor(const GPUPower_Limit_Descriptor& from) : GPUPower_Limit_Descriptor(nullptr, from) {}
  inline GPUPower_Limit_Descriptor(GPUPower_Limit_Descriptor&& from) noexcept
      : GPUPower_Limit_Descriptor(nullptr, ::std::move(from)) {}
  inline GPUPower_Limit_Descriptor& operator=(const GPUPower_Limit_Descriptor& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPUPower_Limit_Descriptor& operator=(GPUPower_Limit_Descriptor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GPUPower_Limit_Descriptor& default_instance() {
    return *reinterpret_cast<const GPUPower_Limit_Descriptor*>(
        &_GPUPower_Limit_Descriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GPUPower_Limit_Descriptor& a, GPUPower_Limit_Descriptor& b) { a.Swap(&b); }
  inline void Swap(GPUPower_Limit_Descriptor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GPUPower_Limit_Descriptor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GPUPower_Limit_Descriptor* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GPUPower_Limit_Descriptor>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GPUPower_Limit_Descriptor& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GPUPower_Limit_Descriptor& from) { GPUPower_Limit_Descriptor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GPUPower_Limit_Descriptor* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.GPUPower.Limit.Descriptor"; }

  explicit GPUPower_Limit_Descriptor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GPUPower_Limit_Descriptor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GPUPower_Limit_Descriptor& from);
  GPUPower_Limit_Descriptor(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GPUPower_Limit_Descriptor&& from) noexcept
      : GPUPower_Limit_Descriptor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStepsFieldNumber = 6,
    kDefaultValueFieldNumber = 1,
    kDisplayNameFieldNumber = 2,
    kMinValueFieldNumber = 3,
    kMaxValueFieldNumber = 4,
    kScalarIncrementFieldNumber = 5,
    kTypeFieldNumber = 7,
    kSupportedFieldNumber = 8,
  };
  // repeated uint32 steps = 6;
  int steps_size() const;
  private:
  int _internal_steps_size() const;

  public:
  void clear_steps() ;
  ::uint32_t steps(int index) const;
  void set_steps(int index, ::uint32_t value);
  void add_steps(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& steps() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_steps();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_steps() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_steps();

  public:
  // uint32 default_value = 1;
  bool has_default_value() const;
  void clear_default_value() ;
  ::uint32_t default_value() const;
  void set_default_value(::uint32_t value);

  private:
  ::uint32_t _internal_default_value() const;
  void _internal_set_default_value(::uint32_t value);

  public:
  // uint32 display_name = 2;
  bool has_display_name() const;
  void clear_display_name() ;
  ::uint32_t display_name() const;
  void set_display_name(::uint32_t value);

  private:
  ::uint32_t _internal_display_name() const;
  void _internal_set_display_name(::uint32_t value);

  public:
  // uint32 min_value = 3;
  bool has_min_value() const;
  void clear_min_value() ;
  ::uint32_t min_value() const;
  void set_min_value(::uint32_t value);

  private:
  ::uint32_t _internal_min_value() const;
  void _internal_set_min_value(::uint32_t value);

  public:
  // uint32 max_value = 4;
  bool has_max_value() const;
  void clear_max_value() ;
  ::uint32_t max_value() const;
  void set_max_value(::uint32_t value);

  private:
  ::uint32_t _internal_max_value() const;
  void _internal_set_max_value(::uint32_t value);

  public:
  // uint32 scalar_increment = 5;
  bool has_scalar_increment() const;
  void clear_scalar_increment() ;
  ::uint32_t scalar_increment() const;
  void set_scalar_increment(::uint32_t value);

  private:
  ::uint32_t _internal_scalar_increment() const;
  void _internal_set_scalar_increment(::uint32_t value);

  public:
  // uint32 type = 7;
  bool has_type() const;
  void clear_type() ;
  ::uint32_t type() const;
  void set_type(::uint32_t value);

  private:
  ::uint32_t _internal_type() const;
  void _internal_set_type(::uint32_t value);

  public:
  // uint32 supported = 8;
  bool has_supported() const;
  void clear_supported() ;
  ::uint32_t supported() const;
  void set_supported(::uint32_t value);

  private:
  ::uint32_t _internal_supported() const;
  void _internal_set_supported(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.GPUPower.Limit.Descriptor)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GPUPower_Limit_Descriptor& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> steps_;
    ::google::protobuf::internal::CachedSize _steps_cached_byte_size_;
    ::uint32_t default_value_;
    ::uint32_t display_name_;
    ::uint32_t min_value_;
    ::uint32_t max_value_;
    ::uint32_t scalar_increment_;
    ::uint32_t type_;
    ::uint32_t supported_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GPUPower_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_Descriptor_class_data_;
// -------------------------------------------------------------------

class GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::int32_t, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::int32_t, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_GPUPower_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class GPUPower_Limit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.GPUPower.Limit) */ {
 public:
  inline GPUPower_Limit() : GPUPower_Limit(nullptr) {}
  ~GPUPower_Limit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GPUPower_Limit* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GPUPower_Limit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GPUPower_Limit(::google::protobuf::internal::ConstantInitialized);

  inline GPUPower_Limit(const GPUPower_Limit& from) : GPUPower_Limit(nullptr, from) {}
  inline GPUPower_Limit(GPUPower_Limit&& from) noexcept
      : GPUPower_Limit(nullptr, ::std::move(from)) {}
  inline GPUPower_Limit& operator=(const GPUPower_Limit& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPUPower_Limit& operator=(GPUPower_Limit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GPUPower_Limit& default_instance() {
    return *reinterpret_cast<const GPUPower_Limit*>(
        &_GPUPower_Limit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GPUPower_Limit& a, GPUPower_Limit& b) { a.Swap(&b); }
  inline void Swap(GPUPower_Limit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GPUPower_Limit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GPUPower_Limit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GPUPower_Limit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GPUPower_Limit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GPUPower_Limit& from) { GPUPower_Limit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GPUPower_Limit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.GPUPower.Limit"; }

  explicit GPUPower_Limit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GPUPower_Limit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GPUPower_Limit& from);
  GPUPower_Limit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GPUPower_Limit&& from) noexcept
      : GPUPower_Limit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Descriptor = GPUPower_Limit_Descriptor;

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentValueFieldNumber = 1,
    kModeDescriptorMapFieldNumber = 2,
  };
  // uint32 current_value = 1;
  bool has_current_value() const;
  void clear_current_value() ;
  ::uint32_t current_value() const;
  void set_current_value(::uint32_t value);

  private:
  ::uint32_t _internal_current_value() const;
  void _internal_set_current_value(::uint32_t value);

  public:
  // map<int32, .legion.messages.GPUPower.Limit.Descriptor> mode_descriptor_map = 2;
  int mode_descriptor_map_size() const;
  private:
  int _internal_mode_descriptor_map_size() const;

  public:
  void clear_mode_descriptor_map() ;
  const ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>& mode_descriptor_map() const;
  ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>* PROTOBUF_NONNULL mutable_mode_descriptor_map();

  private:
  const ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>& _internal_mode_descriptor_map() const;
  ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>* PROTOBUF_NONNULL _internal_mutable_mode_descriptor_map();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.GPUPower.Limit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GPUPower_Limit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t current_value_;
    ::google::protobuf::internal::MapField<GPUPower_Limit_ModeDescriptorMapEntry_DoNotUse, ::int32_t, ::legion::messages::GPUPower_Limit_Descriptor,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        mode_descriptor_map_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GPUPower_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GPUPower_Limit_class_data_;
// -------------------------------------------------------------------

class GPUPower final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.GPUPower) */ {
 public:
  inline GPUPower() : GPUPower(nullptr) {}
  ~GPUPower() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GPUPower* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GPUPower));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GPUPower(::google::protobuf::internal::ConstantInitialized);

  inline GPUPower(const GPUPower& from) : GPUPower(nullptr, from) {}
  inline GPUPower(GPUPower&& from) noexcept
      : GPUPower(nullptr, ::std::move(from)) {}
  inline GPUPower& operator=(const GPUPower& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPUPower& operator=(GPUPower&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GPUPower& default_instance() {
    return *reinterpret_cast<const GPUPower*>(
        &_GPUPower_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(GPUPower& a, GPUPower& b) { a.Swap(&b); }
  inline void Swap(GPUPower* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GPUPower* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GPUPower* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GPUPower>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GPUPower& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GPUPower& from) { GPUPower::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GPUPower* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.GPUPower"; }

  explicit GPUPower(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GPUPower(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GPUPower& from);
  GPUPower(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GPUPower&& from) noexcept
      : GPUPower(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Limit = GPUPower_Limit;

  // accessors -------------------------------------------------------
  enum : int {
    kGpuConfigurableTgpFieldNumber = 1,
    kGpuPowerBoostFieldNumber = 2,
    kGpuTemperatureLimitFieldNumber = 3,
  };
  // .legion.messages.GPUPower.Limit gpu_configurable_tgp = 1;
  bool has_gpu_configurable_tgp() const;
  void clear_gpu_configurable_tgp() ;
  const ::legion::messages::GPUPower_Limit& gpu_configurable_tgp() const;
  [[nodiscard]] ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE release_gpu_configurable_tgp();
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL mutable_gpu_configurable_tgp();
  void set_allocated_gpu_configurable_tgp(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_gpu_configurable_tgp(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE unsafe_arena_release_gpu_configurable_tgp();

  private:
  const ::legion::messages::GPUPower_Limit& _internal_gpu_configurable_tgp() const;
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL _internal_mutable_gpu_configurable_tgp();

  public:
  // .legion.messages.GPUPower.Limit gpu_power_boost = 2;
  bool has_gpu_power_boost() const;
  void clear_gpu_power_boost() ;
  const ::legion::messages::GPUPower_Limit& gpu_power_boost() const;
  [[nodiscard]] ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE release_gpu_power_boost();
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL mutable_gpu_power_boost();
  void set_allocated_gpu_power_boost(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_gpu_power_boost(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE unsafe_arena_release_gpu_power_boost();

  private:
  const ::legion::messages::GPUPower_Limit& _internal_gpu_power_boost() const;
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL _internal_mutable_gpu_power_boost();

  public:
  // .legion.messages.GPUPower.Limit gpu_temperature_limit = 3;
  bool has_gpu_temperature_limit() const;
  void clear_gpu_temperature_limit() ;
  const ::legion::messages::GPUPower_Limit& gpu_temperature_limit() const;
  [[nodiscard]] ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE release_gpu_temperature_limit();
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL mutable_gpu_temperature_limit();
  void set_allocated_gpu_temperature_limit(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_gpu_temperature_limit(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value);
  ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE unsafe_arena_release_gpu_temperature_limit();

  private:
  const ::legion::messages::GPUPower_Limit& _internal_gpu_temperature_limit() const;
  ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL _internal_mutable_gpu_temperature_limit();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.GPUPower)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GPUPower& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE gpu_configurable_tgp_;
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE gpu_power_boost_;
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE gpu_temperature_limit_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GPUPower_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GPUPower_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GPUPower_Limit_Descriptor

// uint32 default_value = 1;
inline bool GPUPower_Limit_Descriptor::has_default_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_default_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.default_value_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::default_value() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.default_value)
  return _internal_default_value();
}
inline void GPUPower_Limit_Descriptor::set_default_value(::uint32_t value) {
  _internal_set_default_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.default_value)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_default_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.default_value_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_default_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.default_value_ = value;
}

// uint32 display_name = 2;
inline bool GPUPower_Limit_Descriptor::has_display_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::display_name() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.display_name)
  return _internal_display_name();
}
inline void GPUPower_Limit_Descriptor::set_display_name(::uint32_t value) {
  _internal_set_display_name(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.display_name)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_display_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.display_name_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_display_name(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_ = value;
}

// uint32 min_value = 3;
inline bool GPUPower_Limit_Descriptor::has_min_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_min_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_value_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::min_value() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.min_value)
  return _internal_min_value();
}
inline void GPUPower_Limit_Descriptor::set_min_value(::uint32_t value) {
  _internal_set_min_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.min_value)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_min_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_value_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_min_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_value_ = value;
}

// uint32 max_value = 4;
inline bool GPUPower_Limit_Descriptor::has_max_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_max_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_value_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::max_value() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.max_value)
  return _internal_max_value();
}
inline void GPUPower_Limit_Descriptor::set_max_value(::uint32_t value) {
  _internal_set_max_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.max_value)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_max_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_value_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_max_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_value_ = value;
}

// uint32 scalar_increment = 5;
inline bool GPUPower_Limit_Descriptor::has_scalar_increment() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_scalar_increment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scalar_increment_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::scalar_increment() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.scalar_increment)
  return _internal_scalar_increment();
}
inline void GPUPower_Limit_Descriptor::set_scalar_increment(::uint32_t value) {
  _internal_set_scalar_increment(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.scalar_increment)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_scalar_increment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scalar_increment_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_scalar_increment(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scalar_increment_ = value;
}

// repeated uint32 steps = 6;
inline int GPUPower_Limit_Descriptor::_internal_steps_size() const {
  return _internal_steps().size();
}
inline int GPUPower_Limit_Descriptor::steps_size() const {
  return _internal_steps_size();
}
inline void GPUPower_Limit_Descriptor::clear_steps() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steps_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::steps(int index) const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.steps)
  return _internal_steps().Get(index);
}
inline void GPUPower_Limit_Descriptor::set_steps(int index, ::uint32_t value) {
  _internal_mutable_steps()->Set(index, value);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.steps)
}
inline void GPUPower_Limit_Descriptor::add_steps(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_steps()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:legion.messages.GPUPower.Limit.Descriptor.steps)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& GPUPower_Limit_Descriptor::steps() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:legion.messages.GPUPower.Limit.Descriptor.steps)
  return _internal_steps();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL GPUPower_Limit_Descriptor::mutable_steps()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:legion.messages.GPUPower.Limit.Descriptor.steps)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_steps();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
GPUPower_Limit_Descriptor::_internal_steps() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.steps_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
GPUPower_Limit_Descriptor::_internal_mutable_steps() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.steps_;
}

// uint32 type = 7;
inline bool GPUPower_Limit_Descriptor::has_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::type() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.type)
  return _internal_type();
}
inline void GPUPower_Limit_Descriptor::set_type(::uint32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.type)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_type(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint32 supported = 8;
inline bool GPUPower_Limit_Descriptor::has_supported() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void GPUPower_Limit_Descriptor::clear_supported() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.supported_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::uint32_t GPUPower_Limit_Descriptor::supported() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.Descriptor.supported)
  return _internal_supported();
}
inline void GPUPower_Limit_Descriptor::set_supported(::uint32_t value) {
  _internal_set_supported(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.Descriptor.supported)
}
inline ::uint32_t GPUPower_Limit_Descriptor::_internal_supported() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.supported_;
}
inline void GPUPower_Limit_Descriptor::_internal_set_supported(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.supported_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GPUPower_Limit

// uint32 current_value = 1;
inline bool GPUPower_Limit::has_current_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void GPUPower_Limit::clear_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_value_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t GPUPower_Limit::current_value() const {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.Limit.current_value)
  return _internal_current_value();
}
inline void GPUPower_Limit::set_current_value(::uint32_t value) {
  _internal_set_current_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.GPUPower.Limit.current_value)
}
inline ::uint32_t GPUPower_Limit::_internal_current_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_value_;
}
inline void GPUPower_Limit::_internal_set_current_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_value_ = value;
}

// map<int32, .legion.messages.GPUPower.Limit.Descriptor> mode_descriptor_map = 2;
inline int GPUPower_Limit::_internal_mode_descriptor_map_size() const {
  return _internal_mode_descriptor_map().size();
}
inline int GPUPower_Limit::mode_descriptor_map_size() const {
  return _internal_mode_descriptor_map_size();
}
inline void GPUPower_Limit::clear_mode_descriptor_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_descriptor_map_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>& GPUPower_Limit::_internal_mode_descriptor_map() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mode_descriptor_map_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>& GPUPower_Limit::mode_descriptor_map() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:legion.messages.GPUPower.Limit.mode_descriptor_map)
  return _internal_mode_descriptor_map();
}
inline ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>* PROTOBUF_NONNULL GPUPower_Limit::_internal_mutable_mode_descriptor_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mode_descriptor_map_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::legion::messages::GPUPower_Limit_Descriptor>* PROTOBUF_NONNULL GPUPower_Limit::mutable_mode_descriptor_map()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_map:legion.messages.GPUPower.Limit.mode_descriptor_map)
  return _internal_mutable_mode_descriptor_map();
}

// -------------------------------------------------------------------

// GPUPower

// .legion.messages.GPUPower.Limit gpu_configurable_tgp = 1;
inline bool GPUPower::has_gpu_configurable_tgp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.gpu_configurable_tgp_ != nullptr);
  return value;
}
inline void GPUPower::clear_gpu_configurable_tgp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_configurable_tgp_ != nullptr) _impl_.gpu_configurable_tgp_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::_internal_gpu_configurable_tgp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::GPUPower_Limit* p = _impl_.gpu_configurable_tgp_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::GPUPower_Limit&>(::legion::messages::_GPUPower_Limit_default_instance_);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::gpu_configurable_tgp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.gpu_configurable_tgp)
  return _internal_gpu_configurable_tgp();
}
inline void GPUPower::unsafe_arena_set_allocated_gpu_configurable_tgp(
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_configurable_tgp_);
  }
  _impl_.gpu_configurable_tgp_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.GPUPower.gpu_configurable_tgp)
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::release_gpu_configurable_tgp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::GPUPower_Limit* released = _impl_.gpu_configurable_tgp_;
  _impl_.gpu_configurable_tgp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::unsafe_arena_release_gpu_configurable_tgp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.GPUPower.gpu_configurable_tgp)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::GPUPower_Limit* temp = _impl_.gpu_configurable_tgp_;
  _impl_.gpu_configurable_tgp_ = nullptr;
  return temp;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::_internal_mutable_gpu_configurable_tgp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_configurable_tgp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::GPUPower_Limit>(GetArena());
    _impl_.gpu_configurable_tgp_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(p);
  }
  return _impl_.gpu_configurable_tgp_;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::mutable_gpu_configurable_tgp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::GPUPower_Limit* _msg = _internal_mutable_gpu_configurable_tgp();
  // @@protoc_insertion_point(field_mutable:legion.messages.GPUPower.gpu_configurable_tgp)
  return _msg;
}
inline void GPUPower::set_allocated_gpu_configurable_tgp(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_configurable_tgp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.gpu_configurable_tgp_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.GPUPower.gpu_configurable_tgp)
}

// .legion.messages.GPUPower.Limit gpu_power_boost = 2;
inline bool GPUPower::has_gpu_power_boost() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.gpu_power_boost_ != nullptr);
  return value;
}
inline void GPUPower::clear_gpu_power_boost() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_power_boost_ != nullptr) _impl_.gpu_power_boost_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::_internal_gpu_power_boost() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::GPUPower_Limit* p = _impl_.gpu_power_boost_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::GPUPower_Limit&>(::legion::messages::_GPUPower_Limit_default_instance_);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::gpu_power_boost() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.gpu_power_boost)
  return _internal_gpu_power_boost();
}
inline void GPUPower::unsafe_arena_set_allocated_gpu_power_boost(
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_power_boost_);
  }
  _impl_.gpu_power_boost_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.GPUPower.gpu_power_boost)
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::release_gpu_power_boost() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::GPUPower_Limit* released = _impl_.gpu_power_boost_;
  _impl_.gpu_power_boost_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::unsafe_arena_release_gpu_power_boost() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.GPUPower.gpu_power_boost)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::GPUPower_Limit* temp = _impl_.gpu_power_boost_;
  _impl_.gpu_power_boost_ = nullptr;
  return temp;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::_internal_mutable_gpu_power_boost() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_power_boost_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::GPUPower_Limit>(GetArena());
    _impl_.gpu_power_boost_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(p);
  }
  return _impl_.gpu_power_boost_;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::mutable_gpu_power_boost()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::GPUPower_Limit* _msg = _internal_mutable_gpu_power_boost();
  // @@protoc_insertion_point(field_mutable:legion.messages.GPUPower.gpu_power_boost)
  return _msg;
}
inline void GPUPower::set_allocated_gpu_power_boost(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_power_boost_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.gpu_power_boost_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.GPUPower.gpu_power_boost)
}

// .legion.messages.GPUPower.Limit gpu_temperature_limit = 3;
inline bool GPUPower::has_gpu_temperature_limit() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.gpu_temperature_limit_ != nullptr);
  return value;
}
inline void GPUPower::clear_gpu_temperature_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_temperature_limit_ != nullptr) _impl_.gpu_temperature_limit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::_internal_gpu_temperature_limit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::GPUPower_Limit* p = _impl_.gpu_temperature_limit_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::GPUPower_Limit&>(::legion::messages::_GPUPower_Limit_default_instance_);
}
inline const ::legion::messages::GPUPower_Limit& GPUPower::gpu_temperature_limit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.GPUPower.gpu_temperature_limit)
  return _internal_gpu_temperature_limit();
}
inline void GPUPower::unsafe_arena_set_allocated_gpu_temperature_limit(
    ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_temperature_limit_);
  }
  _impl_.gpu_temperature_limit_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.GPUPower.gpu_temperature_limit)
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::release_gpu_temperature_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::GPUPower_Limit* released = _impl_.gpu_temperature_limit_;
  _impl_.gpu_temperature_limit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE GPUPower::unsafe_arena_release_gpu_temperature_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.GPUPower.gpu_temperature_limit)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::GPUPower_Limit* temp = _impl_.gpu_temperature_limit_;
  _impl_.gpu_temperature_limit_ = nullptr;
  return temp;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::_internal_mutable_gpu_temperature_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gpu_temperature_limit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::GPUPower_Limit>(GetArena());
    _impl_.gpu_temperature_limit_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(p);
  }
  return _impl_.gpu_temperature_limit_;
}
inline ::legion::messages::GPUPower_Limit* PROTOBUF_NONNULL GPUPower::mutable_gpu_temperature_limit()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::legion::messages::GPUPower_Limit* _msg = _internal_mutable_gpu_temperature_limit();
  // @@protoc_insertion_point(field_mutable:legion.messages.GPUPower.gpu_temperature_limit)
  return _msg;
}
inline void GPUPower::set_allocated_gpu_temperature_limit(::legion::messages::GPUPower_Limit* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.gpu_temperature_limit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.gpu_temperature_limit_ = reinterpret_cast<::legion::messages::GPUPower_Limit*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.GPUPower.gpu_temperature_limit)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GPUPower_2eproto_2epb_2eh
