// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Other.proto
// Protobuf C++ Version: 6.33.1

#include "Other.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace legion {
namespace messages {

inline constexpr OtherSettings_EnableDisableValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        current_{false},
        supported_{false} {}

template <typename>
PROTOBUF_CONSTEXPR OtherSettings_EnableDisableValue::OtherSettings_EnableDisableValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OtherSettings_EnableDisableValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OtherSettings_EnableDisableValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OtherSettings_EnableDisableValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OtherSettings_EnableDisableValueDefaultTypeInternal() {}
  union {
    OtherSettings_EnableDisableValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OtherSettings_EnableDisableValueDefaultTypeInternal _OtherSettings_EnableDisableValue_default_instance_;

inline constexpr GpuSwitchValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        current_{static_cast< ::legion::messages::GpuSwitchValue_HybridModeState >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR GpuSwitchValue::GpuSwitchValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GpuSwitchValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GpuSwitchValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GpuSwitchValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GpuSwitchValueDefaultTypeInternal() {}
  union {
    GpuSwitchValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GpuSwitchValueDefaultTypeInternal _GpuSwitchValue_default_instance_;

inline constexpr OtherSettings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        touch_pad_{nullptr},
        win_key_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR OtherSettings::OtherSettings(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OtherSettings_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OtherSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OtherSettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OtherSettingsDefaultTypeInternal() {}
  union {
    OtherSettings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OtherSettingsDefaultTypeInternal _OtherSettings_default_instance_;
}  // namespace messages
}  // namespace legion
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_Other_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Other_2eproto = nullptr;
const ::uint32_t
    TableStruct_Other_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings_EnableDisableValue, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings_EnableDisableValue, _impl_.current_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings_EnableDisableValue, _impl_.supported_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings, _impl_.touch_pad_),
        PROTOBUF_FIELD_OFFSET(::legion::messages::OtherSettings, _impl_.win_key_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::legion::messages::GpuSwitchValue, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::legion::messages::GpuSwitchValue, _impl_.current_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::legion::messages::OtherSettings_EnableDisableValue)},
        {7, sizeof(::legion::messages::OtherSettings)},
        {14, sizeof(::legion::messages::GpuSwitchValue)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::legion::messages::_OtherSettings_EnableDisableValue_default_instance_._instance,
    &::legion::messages::_OtherSettings_default_instance_._instance,
    &::legion::messages::_GpuSwitchValue_default_instance_._instance,
};
const char descriptor_table_protodef_Other_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013Other.proto\022\017legion.messages\"\323\001\n\rOther"
    "Settings\022D\n\ttouch_pad\030\001 \001(\01321.legion.mes"
    "sages.OtherSettings.EnableDisableValue\022B"
    "\n\007win_key\030\002 \001(\01321.legion.messages.OtherS"
    "ettings.EnableDisableValue\0328\n\022EnableDisa"
    "bleValue\022\017\n\007current\030\001 \001(\010\022\021\n\tsupported\030\002"
    " \001(\010\"\302\001\n\016GpuSwitchValue\022@\n\007current\030\001 \001(\016"
    "2/.legion.messages.GpuSwitchValue.Hybrid"
    "ModeState\"n\n\017HybridModeState\022\022\n\016HYBRID_M"
    "ODE_ON\020\000\022\032\n\026HYBRID_MODE_ONIGPUONLY\020\001\022\026\n\022"
    "HYBRID_MODE_ONAUTO\020\002\022\023\n\017HYBRID_MODE_OFF\020"
    "\003b\010editionsp\351\007"
};
static ::absl::once_flag descriptor_table_Other_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Other_2eproto = {
    false,
    false,
    454,
    descriptor_table_protodef_Other_2eproto,
    "Other.proto",
    &descriptor_table_Other_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_Other_2eproto::offsets,
    file_level_enum_descriptors_Other_2eproto,
    file_level_service_descriptors_Other_2eproto,
};
namespace legion {
namespace messages {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GpuSwitchValue_HybridModeState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Other_2eproto);
  return file_level_enum_descriptors_Other_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GpuSwitchValue_HybridModeState_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class OtherSettings_EnableDisableValue::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<OtherSettings_EnableDisableValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_._has_bits_);
};

OtherSettings_EnableDisableValue::OtherSettings_EnableDisableValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OtherSettings_EnableDisableValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.OtherSettings.EnableDisableValue)
}
OtherSettings_EnableDisableValue::OtherSettings_EnableDisableValue(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OtherSettings_EnableDisableValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OtherSettings_EnableDisableValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE OtherSettings_EnableDisableValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void OtherSettings_EnableDisableValue::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, current_),
           0,
           offsetof(Impl_, supported_) -
               offsetof(Impl_, current_) +
               sizeof(Impl_::supported_));
}
OtherSettings_EnableDisableValue::~OtherSettings_EnableDisableValue() {
  // @@protoc_insertion_point(destructor:legion.messages.OtherSettings.EnableDisableValue)
  SharedDtor(*this);
}
inline void OtherSettings_EnableDisableValue::SharedDtor(MessageLite& self) {
  OtherSettings_EnableDisableValue& this_ = static_cast<OtherSettings_EnableDisableValue&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OtherSettings_EnableDisableValue::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OtherSettings_EnableDisableValue(arena);
}
constexpr auto OtherSettings_EnableDisableValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OtherSettings_EnableDisableValue),
                                            alignof(OtherSettings_EnableDisableValue));
}
constexpr auto OtherSettings_EnableDisableValue::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OtherSettings_EnableDisableValue_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OtherSettings_EnableDisableValue::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OtherSettings_EnableDisableValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OtherSettings_EnableDisableValue::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OtherSettings_EnableDisableValue>(), &OtherSettings_EnableDisableValue::ByteSizeLong,
              &OtherSettings_EnableDisableValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_._cached_size_),
          false,
      },
      &OtherSettings_EnableDisableValue::kDescriptorMethods,
      &descriptor_table_Other_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OtherSettings_EnableDisableValue_class_data_ =
        OtherSettings_EnableDisableValue::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OtherSettings_EnableDisableValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OtherSettings_EnableDisableValue_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OtherSettings_EnableDisableValue_class_data_.tc_table);
  return OtherSettings_EnableDisableValue_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
OtherSettings_EnableDisableValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OtherSettings_EnableDisableValue_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::OtherSettings_EnableDisableValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool supported = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(OtherSettings_EnableDisableValue, _impl_.supported_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.supported_)}},
    // bool current = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(OtherSettings_EnableDisableValue, _impl_.current_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.current_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool current = 1;
    {PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.current_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool supported = 2;
    {PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.supported_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void OtherSettings_EnableDisableValue::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.OtherSettings.EnableDisableValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.current_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.supported_) -
      reinterpret_cast<char*>(&_impl_.current_)) + sizeof(_impl_.supported_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OtherSettings_EnableDisableValue::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OtherSettings_EnableDisableValue& this_ = static_cast<const OtherSettings_EnableDisableValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OtherSettings_EnableDisableValue::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OtherSettings_EnableDisableValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.OtherSettings.EnableDisableValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool current = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_current(), target);
  }

  // bool supported = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_supported(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.OtherSettings.EnableDisableValue)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OtherSettings_EnableDisableValue::ByteSizeLong(const MessageLite& base) {
  const OtherSettings_EnableDisableValue& this_ = static_cast<const OtherSettings_EnableDisableValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OtherSettings_EnableDisableValue::ByteSizeLong() const {
  const OtherSettings_EnableDisableValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.OtherSettings.EnableDisableValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000003U & cached_has_bits) * 2;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OtherSettings_EnableDisableValue::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<OtherSettings_EnableDisableValue*>(&to_msg);
  auto& from = static_cast<const OtherSettings_EnableDisableValue&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.OtherSettings.EnableDisableValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.current_ = from._impl_.current_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.supported_ = from._impl_.supported_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void OtherSettings_EnableDisableValue::CopyFrom(const OtherSettings_EnableDisableValue& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.OtherSettings.EnableDisableValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OtherSettings_EnableDisableValue::InternalSwap(OtherSettings_EnableDisableValue* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.supported_)
      + sizeof(OtherSettings_EnableDisableValue::_impl_.supported_)
      - PROTOBUF_FIELD_OFFSET(OtherSettings_EnableDisableValue, _impl_.current_)>(
          reinterpret_cast<char*>(&_impl_.current_),
          reinterpret_cast<char*>(&other->_impl_.current_));
}

::google::protobuf::Metadata OtherSettings_EnableDisableValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OtherSettings::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<OtherSettings>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_._has_bits_);
};

OtherSettings::OtherSettings(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OtherSettings_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.OtherSettings)
}
PROTOBUF_NDEBUG_INLINE OtherSettings::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::legion::messages::OtherSettings& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

OtherSettings::OtherSettings(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OtherSettings& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OtherSettings_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OtherSettings* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.touch_pad_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.touch_pad_)
                : nullptr;
  _impl_.win_key_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.win_key_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:legion.messages.OtherSettings)
}
PROTOBUF_NDEBUG_INLINE OtherSettings::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void OtherSettings::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, touch_pad_),
           0,
           offsetof(Impl_, win_key_) -
               offsetof(Impl_, touch_pad_) +
               sizeof(Impl_::win_key_));
}
OtherSettings::~OtherSettings() {
  // @@protoc_insertion_point(destructor:legion.messages.OtherSettings)
  SharedDtor(*this);
}
inline void OtherSettings::SharedDtor(MessageLite& self) {
  OtherSettings& this_ = static_cast<OtherSettings&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.touch_pad_;
  delete this_._impl_.win_key_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OtherSettings::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OtherSettings(arena);
}
constexpr auto OtherSettings::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OtherSettings),
                                            alignof(OtherSettings));
}
constexpr auto OtherSettings::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OtherSettings_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OtherSettings::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OtherSettings>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OtherSettings::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OtherSettings>(), &OtherSettings::ByteSizeLong,
              &OtherSettings::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_._cached_size_),
          false,
      },
      &OtherSettings::kDescriptorMethods,
      &descriptor_table_Other_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OtherSettings_class_data_ =
        OtherSettings::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OtherSettings::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OtherSettings_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OtherSettings_class_data_.tc_table);
  return OtherSettings_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
OtherSettings::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    OtherSettings_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::OtherSettings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.win_key_)}},
    // .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.touch_pad_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
    {PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.touch_pad_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
    {PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.win_key_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::legion::messages::OtherSettings_EnableDisableValue>()},
      {::_pbi::TcParser::GetTable<::legion::messages::OtherSettings_EnableDisableValue>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void OtherSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.OtherSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.touch_pad_ != nullptr);
      _impl_.touch_pad_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.win_key_ != nullptr);
      _impl_.win_key_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OtherSettings::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OtherSettings& this_ = static_cast<const OtherSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OtherSettings::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OtherSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.OtherSettings)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.touch_pad_, this_._impl_.touch_pad_->GetCachedSize(), target,
        stream);
  }

  // .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.win_key_, this_._impl_.win_key_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.OtherSettings)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OtherSettings::ByteSizeLong(const MessageLite& base) {
  const OtherSettings& this_ = static_cast<const OtherSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OtherSettings::ByteSizeLong() const {
  const OtherSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.OtherSettings)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.touch_pad_);
    }
    // .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.win_key_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OtherSettings::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<OtherSettings*>(&to_msg);
  auto& from = static_cast<const OtherSettings&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.OtherSettings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.touch_pad_ != nullptr);
      if (_this->_impl_.touch_pad_ == nullptr) {
        _this->_impl_.touch_pad_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.touch_pad_);
      } else {
        _this->_impl_.touch_pad_->MergeFrom(*from._impl_.touch_pad_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.win_key_ != nullptr);
      if (_this->_impl_.win_key_ == nullptr) {
        _this->_impl_.win_key_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.win_key_);
      } else {
        _this->_impl_.win_key_->MergeFrom(*from._impl_.win_key_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void OtherSettings::CopyFrom(const OtherSettings& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.OtherSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OtherSettings::InternalSwap(OtherSettings* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.win_key_)
      + sizeof(OtherSettings::_impl_.win_key_)
      - PROTOBUF_FIELD_OFFSET(OtherSettings, _impl_.touch_pad_)>(
          reinterpret_cast<char*>(&_impl_.touch_pad_),
          reinterpret_cast<char*>(&other->_impl_.touch_pad_));
}

::google::protobuf::Metadata OtherSettings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GpuSwitchValue::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GpuSwitchValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GpuSwitchValue, _impl_._has_bits_);
};

GpuSwitchValue::GpuSwitchValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GpuSwitchValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.messages.GpuSwitchValue)
}
GpuSwitchValue::GpuSwitchValue(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GpuSwitchValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GpuSwitchValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE GpuSwitchValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GpuSwitchValue::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.current_ = {};
}
GpuSwitchValue::~GpuSwitchValue() {
  // @@protoc_insertion_point(destructor:legion.messages.GpuSwitchValue)
  SharedDtor(*this);
}
inline void GpuSwitchValue::SharedDtor(MessageLite& self) {
  GpuSwitchValue& this_ = static_cast<GpuSwitchValue&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GpuSwitchValue::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GpuSwitchValue(arena);
}
constexpr auto GpuSwitchValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GpuSwitchValue),
                                            alignof(GpuSwitchValue));
}
constexpr auto GpuSwitchValue::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GpuSwitchValue_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GpuSwitchValue::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GpuSwitchValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GpuSwitchValue::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GpuSwitchValue>(), &GpuSwitchValue::ByteSizeLong,
              &GpuSwitchValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GpuSwitchValue, _impl_._cached_size_),
          false,
      },
      &GpuSwitchValue::kDescriptorMethods,
      &descriptor_table_Other_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GpuSwitchValue_class_data_ =
        GpuSwitchValue::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GpuSwitchValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GpuSwitchValue_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GpuSwitchValue_class_data_.tc_table);
  return GpuSwitchValue_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
GpuSwitchValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GpuSwitchValue, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GpuSwitchValue_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::legion::messages::GpuSwitchValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .legion.messages.GpuSwitchValue.HybridModeState current = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GpuSwitchValue, _impl_.current_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(GpuSwitchValue, _impl_.current_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .legion.messages.GpuSwitchValue.HybridModeState current = 1;
    {PROTOBUF_FIELD_OFFSET(GpuSwitchValue, _impl_.current_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GpuSwitchValue::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.messages.GpuSwitchValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.current_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GpuSwitchValue::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GpuSwitchValue& this_ = static_cast<const GpuSwitchValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GpuSwitchValue::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GpuSwitchValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:legion.messages.GpuSwitchValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .legion.messages.GpuSwitchValue.HybridModeState current = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_current(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.messages.GpuSwitchValue)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GpuSwitchValue::ByteSizeLong(const MessageLite& base) {
  const GpuSwitchValue& this_ = static_cast<const GpuSwitchValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GpuSwitchValue::ByteSizeLong() const {
  const GpuSwitchValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:legion.messages.GpuSwitchValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .legion.messages.GpuSwitchValue.HybridModeState current = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_current());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GpuSwitchValue::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GpuSwitchValue*>(&to_msg);
  auto& from = static_cast<const GpuSwitchValue&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:legion.messages.GpuSwitchValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.current_ = from._impl_.current_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GpuSwitchValue::CopyFrom(const GpuSwitchValue& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:legion.messages.GpuSwitchValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GpuSwitchValue::InternalSwap(GpuSwitchValue* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.current_, other->_impl_.current_);
}

::google::protobuf::Metadata GpuSwitchValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Other_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
