// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Other.proto
// Protobuf C++ Version: 6.33.1

#ifndef Other_2eproto_2epb_2eh
#define Other_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Other_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Other_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Other_2eproto;
}  // extern "C"
namespace legion {
namespace messages {
enum GpuSwitchValue_HybridModeState : int;
extern const uint32_t GpuSwitchValue_HybridModeState_internal_data_[];
class GpuSwitchValue;
struct GpuSwitchValueDefaultTypeInternal;
extern GpuSwitchValueDefaultTypeInternal _GpuSwitchValue_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GpuSwitchValue_class_data_;
class OtherSettings;
struct OtherSettingsDefaultTypeInternal;
extern OtherSettingsDefaultTypeInternal _OtherSettings_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OtherSettings_class_data_;
class OtherSettings_EnableDisableValue;
struct OtherSettings_EnableDisableValueDefaultTypeInternal;
extern OtherSettings_EnableDisableValueDefaultTypeInternal _OtherSettings_EnableDisableValue_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OtherSettings_EnableDisableValue_class_data_;
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::legion::messages::GpuSwitchValue_HybridModeState_internal_data_>
    internal::EnumTraitsImpl::value<::legion::messages::GpuSwitchValue_HybridModeState>;
}  // namespace protobuf
}  // namespace google

namespace legion {
namespace messages {
enum GpuSwitchValue_HybridModeState : int {
  GpuSwitchValue_HybridModeState_HYBRID_MODE_ON = 0,
  GpuSwitchValue_HybridModeState_HYBRID_MODE_ONIGPUONLY = 1,
  GpuSwitchValue_HybridModeState_HYBRID_MODE_ONAUTO = 2,
  GpuSwitchValue_HybridModeState_HYBRID_MODE_OFF = 3,
  GpuSwitchValue_HybridModeState_GpuSwitchValue_HybridModeState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GpuSwitchValue_HybridModeState_GpuSwitchValue_HybridModeState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GpuSwitchValue_HybridModeState_internal_data_[];
inline constexpr GpuSwitchValue_HybridModeState GpuSwitchValue_HybridModeState_HybridModeState_MIN =
    static_cast<GpuSwitchValue_HybridModeState>(0);
inline constexpr GpuSwitchValue_HybridModeState GpuSwitchValue_HybridModeState_HybridModeState_MAX =
    static_cast<GpuSwitchValue_HybridModeState>(3);
inline bool GpuSwitchValue_HybridModeState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int GpuSwitchValue_HybridModeState_HybridModeState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GpuSwitchValue_HybridModeState_descriptor();
template <typename T>
::absl::string_view GpuSwitchValue_HybridModeState_Name(T value) {
  static_assert(::std::is_same<T, GpuSwitchValue_HybridModeState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to HybridModeState_Name().");
  return GpuSwitchValue_HybridModeState_Name(static_cast<GpuSwitchValue_HybridModeState>(value));
}
template <>
inline ::absl::string_view GpuSwitchValue_HybridModeState_Name(GpuSwitchValue_HybridModeState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GpuSwitchValue_HybridModeState_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool GpuSwitchValue_HybridModeState_Parse(
    ::absl::string_view name, GpuSwitchValue_HybridModeState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GpuSwitchValue_HybridModeState>(GpuSwitchValue_HybridModeState_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class OtherSettings_EnableDisableValue final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.OtherSettings.EnableDisableValue) */ {
 public:
  inline OtherSettings_EnableDisableValue() : OtherSettings_EnableDisableValue(nullptr) {}
  ~OtherSettings_EnableDisableValue() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OtherSettings_EnableDisableValue* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OtherSettings_EnableDisableValue));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OtherSettings_EnableDisableValue(::google::protobuf::internal::ConstantInitialized);

  inline OtherSettings_EnableDisableValue(const OtherSettings_EnableDisableValue& from) : OtherSettings_EnableDisableValue(nullptr, from) {}
  inline OtherSettings_EnableDisableValue(OtherSettings_EnableDisableValue&& from) noexcept
      : OtherSettings_EnableDisableValue(nullptr, ::std::move(from)) {}
  inline OtherSettings_EnableDisableValue& operator=(const OtherSettings_EnableDisableValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline OtherSettings_EnableDisableValue& operator=(OtherSettings_EnableDisableValue&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OtherSettings_EnableDisableValue& default_instance() {
    return *reinterpret_cast<const OtherSettings_EnableDisableValue*>(
        &_OtherSettings_EnableDisableValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OtherSettings_EnableDisableValue& a, OtherSettings_EnableDisableValue& b) { a.Swap(&b); }
  inline void Swap(OtherSettings_EnableDisableValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OtherSettings_EnableDisableValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OtherSettings_EnableDisableValue* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OtherSettings_EnableDisableValue>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OtherSettings_EnableDisableValue& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OtherSettings_EnableDisableValue& from) { OtherSettings_EnableDisableValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OtherSettings_EnableDisableValue* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.OtherSettings.EnableDisableValue"; }

  explicit OtherSettings_EnableDisableValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OtherSettings_EnableDisableValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OtherSettings_EnableDisableValue& from);
  OtherSettings_EnableDisableValue(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OtherSettings_EnableDisableValue&& from) noexcept
      : OtherSettings_EnableDisableValue(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentFieldNumber = 1,
    kSupportedFieldNumber = 2,
  };
  // bool current = 1;
  bool has_current() const;
  void clear_current() ;
  bool current() const;
  void set_current(bool value);

  private:
  bool _internal_current() const;
  void _internal_set_current(bool value);

  public:
  // bool supported = 2;
  bool has_supported() const;
  void clear_supported() ;
  bool supported() const;
  void set_supported(bool value);

  private:
  bool _internal_supported() const;
  void _internal_set_supported(bool value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.OtherSettings.EnableDisableValue)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OtherSettings_EnableDisableValue& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool current_;
    bool supported_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Other_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OtherSettings_EnableDisableValue_class_data_;
// -------------------------------------------------------------------

class GpuSwitchValue final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.GpuSwitchValue) */ {
 public:
  inline GpuSwitchValue() : GpuSwitchValue(nullptr) {}
  ~GpuSwitchValue() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GpuSwitchValue* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GpuSwitchValue));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GpuSwitchValue(::google::protobuf::internal::ConstantInitialized);

  inline GpuSwitchValue(const GpuSwitchValue& from) : GpuSwitchValue(nullptr, from) {}
  inline GpuSwitchValue(GpuSwitchValue&& from) noexcept
      : GpuSwitchValue(nullptr, ::std::move(from)) {}
  inline GpuSwitchValue& operator=(const GpuSwitchValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline GpuSwitchValue& operator=(GpuSwitchValue&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GpuSwitchValue& default_instance() {
    return *reinterpret_cast<const GpuSwitchValue*>(
        &_GpuSwitchValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GpuSwitchValue& a, GpuSwitchValue& b) { a.Swap(&b); }
  inline void Swap(GpuSwitchValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GpuSwitchValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GpuSwitchValue* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GpuSwitchValue>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GpuSwitchValue& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GpuSwitchValue& from) { GpuSwitchValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GpuSwitchValue* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.GpuSwitchValue"; }

  explicit GpuSwitchValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GpuSwitchValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GpuSwitchValue& from);
  GpuSwitchValue(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GpuSwitchValue&& from) noexcept
      : GpuSwitchValue(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using HybridModeState = GpuSwitchValue_HybridModeState;
  static constexpr HybridModeState HYBRID_MODE_ON = GpuSwitchValue_HybridModeState_HYBRID_MODE_ON;
  static constexpr HybridModeState HYBRID_MODE_ONIGPUONLY = GpuSwitchValue_HybridModeState_HYBRID_MODE_ONIGPUONLY;
  static constexpr HybridModeState HYBRID_MODE_ONAUTO = GpuSwitchValue_HybridModeState_HYBRID_MODE_ONAUTO;
  static constexpr HybridModeState HYBRID_MODE_OFF = GpuSwitchValue_HybridModeState_HYBRID_MODE_OFF;
  static inline bool HybridModeState_IsValid(int value) {
    return GpuSwitchValue_HybridModeState_IsValid(value);
  }
  static constexpr HybridModeState HybridModeState_MIN = GpuSwitchValue_HybridModeState_HybridModeState_MIN;
  static constexpr HybridModeState HybridModeState_MAX = GpuSwitchValue_HybridModeState_HybridModeState_MAX;
  static constexpr int HybridModeState_ARRAYSIZE = GpuSwitchValue_HybridModeState_HybridModeState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HybridModeState_descriptor() {
    return GpuSwitchValue_HybridModeState_descriptor();
  }
  template <typename T>
  static inline ::absl::string_view HybridModeState_Name(T value) {
    return GpuSwitchValue_HybridModeState_Name(value);
  }
  static inline bool HybridModeState_Parse(
      ::absl::string_view name, HybridModeState* PROTOBUF_NONNULL value) {
    return GpuSwitchValue_HybridModeState_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentFieldNumber = 1,
  };
  // .legion.messages.GpuSwitchValue.HybridModeState current = 1;
  bool has_current() const;
  void clear_current() ;
  ::legion::messages::GpuSwitchValue_HybridModeState current() const;
  void set_current(::legion::messages::GpuSwitchValue_HybridModeState value);

  private:
  ::legion::messages::GpuSwitchValue_HybridModeState _internal_current() const;
  void _internal_set_current(::legion::messages::GpuSwitchValue_HybridModeState value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.GpuSwitchValue)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GpuSwitchValue& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int current_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Other_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GpuSwitchValue_class_data_;
// -------------------------------------------------------------------

class OtherSettings final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.OtherSettings) */ {
 public:
  inline OtherSettings() : OtherSettings(nullptr) {}
  ~OtherSettings() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OtherSettings* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OtherSettings));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OtherSettings(::google::protobuf::internal::ConstantInitialized);

  inline OtherSettings(const OtherSettings& from) : OtherSettings(nullptr, from) {}
  inline OtherSettings(OtherSettings&& from) noexcept
      : OtherSettings(nullptr, ::std::move(from)) {}
  inline OtherSettings& operator=(const OtherSettings& from) {
    CopyFrom(from);
    return *this;
  }
  inline OtherSettings& operator=(OtherSettings&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OtherSettings& default_instance() {
    return *reinterpret_cast<const OtherSettings*>(
        &_OtherSettings_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OtherSettings& a, OtherSettings& b) { a.Swap(&b); }
  inline void Swap(OtherSettings* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OtherSettings* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OtherSettings* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OtherSettings>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OtherSettings& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OtherSettings& from) { OtherSettings::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OtherSettings* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.OtherSettings"; }

  explicit OtherSettings(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OtherSettings(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OtherSettings& from);
  OtherSettings(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OtherSettings&& from) noexcept
      : OtherSettings(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using EnableDisableValue = OtherSettings_EnableDisableValue;

  // accessors -------------------------------------------------------
  enum : int {
    kTouchPadFieldNumber = 1,
    kWinKeyFieldNumber = 2,
  };
  // .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
  bool has_touch_pad() const;
  void clear_touch_pad() ;
  const ::legion::messages::OtherSettings_EnableDisableValue& touch_pad() const;
  [[nodiscard]] ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE release_touch_pad();
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL mutable_touch_pad();
  void set_allocated_touch_pad(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_touch_pad(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value);
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE unsafe_arena_release_touch_pad();

  private:
  const ::legion::messages::OtherSettings_EnableDisableValue& _internal_touch_pad() const;
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL _internal_mutable_touch_pad();

  public:
  // .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
  bool has_win_key() const;
  void clear_win_key() ;
  const ::legion::messages::OtherSettings_EnableDisableValue& win_key() const;
  [[nodiscard]] ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE release_win_key();
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL mutable_win_key();
  void set_allocated_win_key(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_win_key(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value);
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE unsafe_arena_release_win_key();

  private:
  const ::legion::messages::OtherSettings_EnableDisableValue& _internal_win_key() const;
  ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL _internal_mutable_win_key();

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.OtherSettings)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OtherSettings& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE touch_pad_;
    ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE win_key_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Other_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OtherSettings_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OtherSettings_EnableDisableValue

// bool current = 1;
inline bool OtherSettings_EnableDisableValue::has_current() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void OtherSettings_EnableDisableValue::clear_current() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool OtherSettings_EnableDisableValue::current() const {
  // @@protoc_insertion_point(field_get:legion.messages.OtherSettings.EnableDisableValue.current)
  return _internal_current();
}
inline void OtherSettings_EnableDisableValue::set_current(bool value) {
  _internal_set_current(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.OtherSettings.EnableDisableValue.current)
}
inline bool OtherSettings_EnableDisableValue::_internal_current() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_;
}
inline void OtherSettings_EnableDisableValue::_internal_set_current(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = value;
}

// bool supported = 2;
inline bool OtherSettings_EnableDisableValue::has_supported() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void OtherSettings_EnableDisableValue::clear_supported() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.supported_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool OtherSettings_EnableDisableValue::supported() const {
  // @@protoc_insertion_point(field_get:legion.messages.OtherSettings.EnableDisableValue.supported)
  return _internal_supported();
}
inline void OtherSettings_EnableDisableValue::set_supported(bool value) {
  _internal_set_supported(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.OtherSettings.EnableDisableValue.supported)
}
inline bool OtherSettings_EnableDisableValue::_internal_supported() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.supported_;
}
inline void OtherSettings_EnableDisableValue::_internal_set_supported(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.supported_ = value;
}

// -------------------------------------------------------------------

// OtherSettings

// .legion.messages.OtherSettings.EnableDisableValue touch_pad = 1;
inline bool OtherSettings::has_touch_pad() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.touch_pad_ != nullptr);
  return value;
}
inline void OtherSettings::clear_touch_pad() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.touch_pad_ != nullptr) _impl_.touch_pad_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::legion::messages::OtherSettings_EnableDisableValue& OtherSettings::_internal_touch_pad() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::OtherSettings_EnableDisableValue* p = _impl_.touch_pad_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::OtherSettings_EnableDisableValue&>(::legion::messages::_OtherSettings_EnableDisableValue_default_instance_);
}
inline const ::legion::messages::OtherSettings_EnableDisableValue& OtherSettings::touch_pad() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.OtherSettings.touch_pad)
  return _internal_touch_pad();
}
inline void OtherSettings::unsafe_arena_set_allocated_touch_pad(
    ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.touch_pad_);
  }
  _impl_.touch_pad_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.OtherSettings.touch_pad)
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE OtherSettings::release_touch_pad() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::OtherSettings_EnableDisableValue* released = _impl_.touch_pad_;
  _impl_.touch_pad_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE OtherSettings::unsafe_arena_release_touch_pad() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.OtherSettings.touch_pad)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::OtherSettings_EnableDisableValue* temp = _impl_.touch_pad_;
  _impl_.touch_pad_ = nullptr;
  return temp;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL OtherSettings::_internal_mutable_touch_pad() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.touch_pad_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::OtherSettings_EnableDisableValue>(GetArena());
    _impl_.touch_pad_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(p);
  }
  return _impl_.touch_pad_;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL OtherSettings::mutable_touch_pad()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::legion::messages::OtherSettings_EnableDisableValue* _msg = _internal_mutable_touch_pad();
  // @@protoc_insertion_point(field_mutable:legion.messages.OtherSettings.touch_pad)
  return _msg;
}
inline void OtherSettings::set_allocated_touch_pad(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.touch_pad_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.touch_pad_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.OtherSettings.touch_pad)
}

// .legion.messages.OtherSettings.EnableDisableValue win_key = 2;
inline bool OtherSettings::has_win_key() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.win_key_ != nullptr);
  return value;
}
inline void OtherSettings::clear_win_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.win_key_ != nullptr) _impl_.win_key_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::legion::messages::OtherSettings_EnableDisableValue& OtherSettings::_internal_win_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::legion::messages::OtherSettings_EnableDisableValue* p = _impl_.win_key_;
  return p != nullptr ? *p : reinterpret_cast<const ::legion::messages::OtherSettings_EnableDisableValue&>(::legion::messages::_OtherSettings_EnableDisableValue_default_instance_);
}
inline const ::legion::messages::OtherSettings_EnableDisableValue& OtherSettings::win_key() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:legion.messages.OtherSettings.win_key)
  return _internal_win_key();
}
inline void OtherSettings::unsafe_arena_set_allocated_win_key(
    ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.win_key_);
  }
  _impl_.win_key_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:legion.messages.OtherSettings.win_key)
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE OtherSettings::release_win_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::OtherSettings_EnableDisableValue* released = _impl_.win_key_;
  _impl_.win_key_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE OtherSettings::unsafe_arena_release_win_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:legion.messages.OtherSettings.win_key)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::OtherSettings_EnableDisableValue* temp = _impl_.win_key_;
  _impl_.win_key_ = nullptr;
  return temp;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL OtherSettings::_internal_mutable_win_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.win_key_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::legion::messages::OtherSettings_EnableDisableValue>(GetArena());
    _impl_.win_key_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(p);
  }
  return _impl_.win_key_;
}
inline ::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NONNULL OtherSettings::mutable_win_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::legion::messages::OtherSettings_EnableDisableValue* _msg = _internal_mutable_win_key();
  // @@protoc_insertion_point(field_mutable:legion.messages.OtherSettings.win_key)
  return _msg;
}
inline void OtherSettings::set_allocated_win_key(::legion::messages::OtherSettings_EnableDisableValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.win_key_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.win_key_ = reinterpret_cast<::legion::messages::OtherSettings_EnableDisableValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:legion.messages.OtherSettings.win_key)
}

// -------------------------------------------------------------------

// GpuSwitchValue

// .legion.messages.GpuSwitchValue.HybridModeState current = 1;
inline bool GpuSwitchValue::has_current() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void GpuSwitchValue::clear_current() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::legion::messages::GpuSwitchValue_HybridModeState GpuSwitchValue::current() const {
  // @@protoc_insertion_point(field_get:legion.messages.GpuSwitchValue.current)
  return _internal_current();
}
inline void GpuSwitchValue::set_current(::legion::messages::GpuSwitchValue_HybridModeState value) {
  _internal_set_current(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.GpuSwitchValue.current)
}
inline ::legion::messages::GpuSwitchValue_HybridModeState GpuSwitchValue::_internal_current() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::legion::messages::GpuSwitchValue_HybridModeState>(_impl_.current_);
}
inline void GpuSwitchValue::_internal_set_current(::legion::messages::GpuSwitchValue_HybridModeState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::legion::messages::GpuSwitchValue_HybridModeState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::legion::messages::GpuSwitchValue_HybridModeState>() {
  return ::legion::messages::GpuSwitchValue_HybridModeState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Other_2eproto_2epb_2eh
