// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PowerProfile.proto
// Protobuf C++ Version: 6.33.1

#ifndef PowerProfile_2eproto_2epb_2eh
#define PowerProfile_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_PowerProfile_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_PowerProfile_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_PowerProfile_2eproto;
}  // extern "C"
namespace legion {
namespace messages {
enum PowerProfile_Profiles : int;
extern const uint32_t PowerProfile_Profiles_internal_data_[];
class PowerProfile;
struct PowerProfileDefaultTypeInternal;
extern PowerProfileDefaultTypeInternal _PowerProfile_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PowerProfile_class_data_;
}  // namespace messages
}  // namespace legion
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::legion::messages::PowerProfile_Profiles_internal_data_>
    internal::EnumTraitsImpl::value<::legion::messages::PowerProfile_Profiles>;
}  // namespace protobuf
}  // namespace google

namespace legion {
namespace messages {
enum PowerProfile_Profiles : int {
  PowerProfile_Profiles_POWER_PROFILE_UNKNOWN = 0,
  PowerProfile_Profiles_POWER_PROFILE_QUIET = 1,
  PowerProfile_Profiles_POWER_PROFILE_BALANCED = 2,
  PowerProfile_Profiles_POWER_PROFILE_PERFORMANCE = 3,
  PowerProfile_Profiles_POWER_PROFILE_EXTREME = 224,
  PowerProfile_Profiles_POWER_PROFILE_CUSTOM = 255,
  PowerProfile_Profiles_PowerProfile_Profiles_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PowerProfile_Profiles_PowerProfile_Profiles_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PowerProfile_Profiles_internal_data_[];
inline constexpr PowerProfile_Profiles PowerProfile_Profiles_Profiles_MIN =
    static_cast<PowerProfile_Profiles>(0);
inline constexpr PowerProfile_Profiles PowerProfile_Profiles_Profiles_MAX =
    static_cast<PowerProfile_Profiles>(255);
inline bool PowerProfile_Profiles_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, PowerProfile_Profiles_internal_data_);
}
inline constexpr int PowerProfile_Profiles_Profiles_ARRAYSIZE = 255 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PowerProfile_Profiles_descriptor();
template <typename T>
::absl::string_view PowerProfile_Profiles_Name(T value) {
  static_assert(::std::is_same<T, PowerProfile_Profiles>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Profiles_Name().");
  return ::google::protobuf::internal::NameOfEnum(PowerProfile_Profiles_descriptor(), value);
}
inline bool PowerProfile_Profiles_Parse(
    ::absl::string_view name, PowerProfile_Profiles* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PowerProfile_Profiles>(PowerProfile_Profiles_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PowerProfile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:legion.messages.PowerProfile) */ {
 public:
  inline PowerProfile() : PowerProfile(nullptr) {}
  ~PowerProfile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PowerProfile* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PowerProfile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PowerProfile(::google::protobuf::internal::ConstantInitialized);

  inline PowerProfile(const PowerProfile& from) : PowerProfile(nullptr, from) {}
  inline PowerProfile(PowerProfile&& from) noexcept
      : PowerProfile(nullptr, ::std::move(from)) {}
  inline PowerProfile& operator=(const PowerProfile& from) {
    CopyFrom(from);
    return *this;
  }
  inline PowerProfile& operator=(PowerProfile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PowerProfile& default_instance() {
    return *reinterpret_cast<const PowerProfile*>(
        &_PowerProfile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PowerProfile& a, PowerProfile& b) { a.Swap(&b); }
  inline void Swap(PowerProfile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PowerProfile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PowerProfile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PowerProfile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PowerProfile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PowerProfile& from) { PowerProfile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PowerProfile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "legion.messages.PowerProfile"; }

  explicit PowerProfile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PowerProfile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PowerProfile& from);
  PowerProfile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PowerProfile&& from) noexcept
      : PowerProfile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Profiles = PowerProfile_Profiles;
  static constexpr Profiles POWER_PROFILE_UNKNOWN = PowerProfile_Profiles_POWER_PROFILE_UNKNOWN;
  static constexpr Profiles POWER_PROFILE_QUIET = PowerProfile_Profiles_POWER_PROFILE_QUIET;
  static constexpr Profiles POWER_PROFILE_BALANCED = PowerProfile_Profiles_POWER_PROFILE_BALANCED;
  static constexpr Profiles POWER_PROFILE_PERFORMANCE = PowerProfile_Profiles_POWER_PROFILE_PERFORMANCE;
  static constexpr Profiles POWER_PROFILE_EXTREME = PowerProfile_Profiles_POWER_PROFILE_EXTREME;
  static constexpr Profiles POWER_PROFILE_CUSTOM = PowerProfile_Profiles_POWER_PROFILE_CUSTOM;
  static inline bool Profiles_IsValid(int value) {
    return PowerProfile_Profiles_IsValid(value);
  }
  static constexpr Profiles Profiles_MIN = PowerProfile_Profiles_Profiles_MIN;
  static constexpr Profiles Profiles_MAX = PowerProfile_Profiles_Profiles_MAX;
  static constexpr int Profiles_ARRAYSIZE = PowerProfile_Profiles_Profiles_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Profiles_descriptor() {
    return PowerProfile_Profiles_descriptor();
  }
  template <typename T>
  static inline ::absl::string_view Profiles_Name(T value) {
    return PowerProfile_Profiles_Name(value);
  }
  static inline bool Profiles_Parse(
      ::absl::string_view name, Profiles* PROTOBUF_NONNULL value) {
    return PowerProfile_Profiles_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentValueFieldNumber = 1,
    kThermalModeFieldNumber = 2,
  };
  // .legion.messages.PowerProfile.Profiles current_value = 1;
  bool has_current_value() const;
  void clear_current_value() ;
  ::legion::messages::PowerProfile_Profiles current_value() const;
  void set_current_value(::legion::messages::PowerProfile_Profiles value);

  private:
  ::legion::messages::PowerProfile_Profiles _internal_current_value() const;
  void _internal_set_current_value(::legion::messages::PowerProfile_Profiles value);

  public:
  // .legion.messages.PowerProfile.Profiles thermal_mode = 2;
  bool has_thermal_mode() const;
  void clear_thermal_mode() ;
  ::legion::messages::PowerProfile_Profiles thermal_mode() const;
  void set_thermal_mode(::legion::messages::PowerProfile_Profiles value);

  private:
  ::legion::messages::PowerProfile_Profiles _internal_thermal_mode() const;
  void _internal_set_thermal_mode(::legion::messages::PowerProfile_Profiles value);

  public:
  // @@protoc_insertion_point(class_scope:legion.messages.PowerProfile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PowerProfile& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int current_value_;
    int thermal_mode_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PowerProfile_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PowerProfile_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PowerProfile

// .legion.messages.PowerProfile.Profiles current_value = 1;
inline bool PowerProfile::has_current_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PowerProfile::clear_current_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::legion::messages::PowerProfile_Profiles PowerProfile::current_value() const {
  // @@protoc_insertion_point(field_get:legion.messages.PowerProfile.current_value)
  return _internal_current_value();
}
inline void PowerProfile::set_current_value(::legion::messages::PowerProfile_Profiles value) {
  _internal_set_current_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:legion.messages.PowerProfile.current_value)
}
inline ::legion::messages::PowerProfile_Profiles PowerProfile::_internal_current_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::legion::messages::PowerProfile_Profiles>(_impl_.current_value_);
}
inline void PowerProfile::_internal_set_current_value(::legion::messages::PowerProfile_Profiles value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_value_ = value;
}

// .legion.messages.PowerProfile.Profiles thermal_mode = 2;
inline bool PowerProfile::has_thermal_mode() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PowerProfile::clear_thermal_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thermal_mode_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::legion::messages::PowerProfile_Profiles PowerProfile::thermal_mode() const {
  // @@protoc_insertion_point(field_get:legion.messages.PowerProfile.thermal_mode)
  return _internal_thermal_mode();
}
inline void PowerProfile::set_thermal_mode(::legion::messages::PowerProfile_Profiles value) {
  _internal_set_thermal_mode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:legion.messages.PowerProfile.thermal_mode)
}
inline ::legion::messages::PowerProfile_Profiles PowerProfile::_internal_thermal_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::legion::messages::PowerProfile_Profiles>(_impl_.thermal_mode_);
}
inline void PowerProfile::_internal_set_thermal_mode(::legion::messages::PowerProfile_Profiles value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thermal_mode_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace legion


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::legion::messages::PowerProfile_Profiles> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::legion::messages::PowerProfile_Profiles>() {
  return ::legion::messages::PowerProfile_Profiles_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // PowerProfile_2eproto_2epb_2eh
